"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import SiteNav from "../components/SiteNav";

type Companion = {name:string; arabic:string; title:string; fact:string; search:string};
const companions:Companion[]=[
{name:"Abu Bakr as-Siddiq",arabic:"أبو بكر الصديق",title:"The truthful friend",fact:"Accompanied the Prophet ﷺ during the Hijrah; mentioned in Qur'an 9:40.",search:"Abu Bakr"},
{name:"Umar ibn al-Khattab",arabic:"عمر بن الخطاب",title:"Al-Faruq",fact:"The second rightly guided caliph, remembered for justice.",search:"Umar ibn al Khattab"},
{name:"Uthman ibn Affan",arabic:"عثمان بن عفان",title:"Dhun-Nurayn",fact:"The third rightly guided caliph; associated with standardizing the written muṣḥaf.",search:"Uthman ibn Affan"},
{name:"Ali ibn Abi Talib",arabic:"علي بن أبي طالب",title:"Cousin of the Prophet ﷺ",fact:"The fourth rightly guided caliph and an early believer.",search:"Ali ibn Abi Talib"},
{name:"Talhah ibn Ubaydillah",arabic:"طلحة بن عبيد الله",title:"A companion of Uhud",fact:"Known for defending the Prophet ﷺ at the Battle of Uhud.",search:"Talha ibn Ubaidullah"},
{name:"Az-Zubayr ibn al-Awwam",arabic:"الزبير بن العوام",title:"A close supporter",fact:"Among the earliest Muslims and a cousin of the Prophet ﷺ.",search:"Zubair ibn Awwam"},
{name:"Abdur-Rahman ibn Awf",arabic:"عبد الرحمن بن عوف",title:"Generous merchant",fact:"An early emigrant remembered for charity and commerce.",search:"Abdur Rahman ibn Awf"},
{name:"Sa'd ibn Abi Waqqas",arabic:"سعد بن أبي وقاص",title:"Early believer",fact:"Among the earliest Muslims and renowned for archery.",search:"Sad ibn Abi Waqqas"},
{name:"Sa'id ibn Zayd",arabic:"سعيد بن زيد",title:"Early believer",fact:"One of the early Muslims and husband of Fatimah bint al-Khattab.",search:"Said ibn Zayd"},
{name:"Abu Ubaydah ibn al-Jarrah",arabic:"أبو عبيدة بن الجراح",title:"Trustworthy of the ummah",fact:"Remembered for integrity and leadership.",search:"Abu Ubaidah ibn al Jarrah"},
{name:"Bilal ibn Rabah",arabic:"بلال بن رباح",title:"The first mu'adhdhin",fact:"Remembered for perseverance under persecution and the call to prayer.",search:"Bilal ibn Rabah"},
{name:"Khadijah bint Khuwaylid",arabic:"خديجة بنت خويلد",title:"Mother of the believers",fact:"The Prophet's ﷺ first wife and first believer in his message.",search:"Khadijah"},
{name:"Aishah bint Abi Bakr",arabic:"عائشة بنت أبي بكر",title:"Scholar and narrator",fact:"A major transmitter of hadith and teacher of the early Muslim community.",search:"Aisha"},
{name:"Umm Salamah",arabic:"أم سلمة",title:"Mother of the believers",fact:"Known for wisdom and narrating prophetic traditions.",search:"Umm Salama"},
{name:"Abu Hurayrah",arabic:"أبو هريرة",title:"Hadith narrator",fact:"Among the most prolific narrators of prophetic reports.",search:"Abu Huraira"},
{name:"Salman al-Farisi",arabic:"سلمان الفارسي",title:"Seeker of truth",fact:"Known for his journey in search of faith and the trench strategy.",search:"Salman al Farisi"},
{name:"Mus'ab ibn Umayr",arabic:"مصعب بن عمير",title:"Early teacher",fact:"Sent to teach Islam in Madinah before the Hijrah.",search:"Musab ibn Umair"},
{name:"Asma bint Abi Bakr",arabic:"أسماء بنت أبي بكر",title:"Dhat an-Nitaqayn",fact:"Helped provision the Prophet's ﷺ journey during the Hijrah.",search:"Asma bint Abu Bakr"}
];
export default function SahabaPage(){
const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Companion|null>(null); const [read,setRead]=useState<string[]>([]);const [slide,setSlide]=useState(0);
useEffect(()=>{try{setRead(JSON.parse(localStorage.getItem("sahaba-read-v1")||"[]"))}catch{}},[]);
const filtered=useMemo(()=>companions.filter(c=>(c.name+" "+c.arabic+" "+c.title+" "+c.fact).toLowerCase().includes(query.toLowerCase())),[query]);
const mark=(name:string)=>{const next=read.includes(name)?read.filter(x=>x!==name):[...read,name];setRead(next);localStorage.setItem("sahaba-read-v1",JSON.stringify(next))};
const featured=companions.slice(0,10);const completed=featured.slice(0,5).filter(c=>read.includes(c.name)).length;
return <main style={{minHeight:"100vh",background:"radial-gradient(circle at top,#203c38,#090f18 65%)",color:"#f4f5ed"}}><SiteNav/><div style={{maxWidth:1180,margin:"auto",padding:"38px 20px 100px"}}>
<Link href="/ashab" style={{color:"#a4e6cb"}}>← أصحاب · Your circle</Link>
<header style={{padding:"50px 0 24px"}}><p style={{letterSpacing:4,color:"#9bdec6"}}>1MUSLIM · LEARN THE LANGUAGE</p><h1 style={{fontSize:"clamp(42px,7vw,86px)",margin:"12px 0"}}>الصحابة <span style={{display:"block",fontSize:".42em",color:"#b3d7ca"}}>As-Sahabah · The Companions</span></h1><p style={{maxWidth:720,lineHeight:1.8}}>On 1Muslim, <b>أصحاب</b> means your companions or mutual connections. <b>الصحابة</b> refers specifically to the Companions of Prophet Muhammad ﷺ. Explore their lives, lessons and narrations.</p></header>
<div style={{padding:22,border:"1px solid #527e70",borderRadius:24,background:"#ffffff0c",marginBottom:26}}><strong>✨ HudHud's Arabic word discovery</strong><p>Whenever you see أصحاب, tap it to learn what the word means and visit this page. The Companions of the Prophet ﷺ are called الصحابة.</p></div>
<section><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><h2>Ten given glad tidings of Paradise</h2><div><button onClick={()=>setSlide((slide+9)%10)} aria-label="Previous companion">←</button> <button onClick={()=>setSlide((slide+1)%10)} aria-label="Next companion">→</button></div></div><p style={{color:"#b4c9c2"}}>All ten are named together in Jamiʿ at-Tirmidhi 3747. This learning journey begins with five.</p>
<div style={{display:"flex",overflowX:"auto",gap:16,padding:"12px 0 24px",scrollSnapType:"x mandatory"}}>{[...featured.slice(slide),...featured.slice(0,slide)].map((c,i)=><button key={c.name} onClick={()=>setSelected(c)} style={{textAlign:"left",flex:"0 0 245px",minHeight:250,padding:22,border:"1px solid #466e60",borderRadius:22,background:"linear-gradient(145deg,#214b44,#14222b)",color:"white",scrollSnapAlign:"start"}}><div style={{fontSize:36,marginBottom:14}}>✦</div><div lang="ar" dir="rtl" style={{fontSize:23}}>{c.arabic}</div><h3>{c.name}</h3><p style={{color:"#bcd4c9"}}>{c.title}</p><small>{read.includes(c.name)?"✓ Read":"Discover →"}</small></button>)}</div>
<div style={{padding:20,borderRadius:20,background:"#16332f"}}><strong>First five reading milestone: {completed}/5</strong><div role="progressbar" aria-valuenow={completed} aria-valuemin={0} aria-valuemax={5} style={{height:9,background:"#36534b",borderRadius:20,margin:"12px 0"}}><div style={{width:(completed*20)+"%",height:"100%",background:"#9be6bd",borderRadius:20}}/></div><p>{completed===5?"🌟 You've marked the first five biographies as read!":"Open each of the first five cards and mark it as read to complete the milestone."}</p></div></section>
<section style={{marginTop:55}}><h2>Explore more الصحابة</h2><label htmlFor="sahaba-search">Search names, Arabic, or lessons</label><input id="sahaba-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the Companions…" style={{display:"block",width:"100%",padding:17,margin:"12px 0 25px",borderRadius:16,border:"1px solid #5a8474",background:"#10201e",color:"white",fontSize:17}}/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14}}>{filtered.map(c=><button key={c.name} onClick={()=>setSelected(c)} style={{textAlign:"left",padding:22,border:"1px solid #45635d",borderRadius:18,background:"#ffffff0b",color:"white"}}><span lang="ar" style={{fontSize:22}}>{c.arabic}</span><h3>{c.name}</h3><p style={{color:"#bad0c7"}}>{c.fact}</p><small>Story · hadith references →</small></button>)}</div>{!filtered.length&&<p>No companions found. Try another spelling.</p>}</section>
{selected&&<div role="dialog" aria-modal="true" aria-label={selected.name} onClick={()=>setSelected(null)} style={{position:"fixed",inset:0,zIndex:9999,background:"#000c",display:"grid",placeItems:"center",padding:18}}><article onClick={e=>e.stopPropagation()} style={{maxWidth:620,width:"100%",maxHeight:"85vh",overflowY:"auto",padding:28,borderRadius:26,background:"#18342f",border:"1px solid #75a997",boxShadow:"0 20px 80px #0009"}}><button onClick={()=>setSelected(null)} style={{float:"right"}} aria-label="Close">✕</button><p lang="ar" dir="rtl" style={{fontSize:32}}>{selected.arabic}</p><h2>{selected.name}</h2><p style={{color:"#bde4d2"}}>{selected.title}</p><p style={{lineHeight:1.8}}>{selected.fact}</p><h3>Explore verified narrations</h3><p>Follow the hadith search below and review the source, grading, and context. A search result is not itself a verified attribution.</p><a target="_blank" rel="noopener noreferrer" href={"https://sunnah.com/search?q="+encodeURIComponent(selected.search)} style={{color:"#b3f4d6"}}>Search hadith mentioning {selected.name} ↗</a><p><a target="_blank" rel="noopener noreferrer" href="https://sunnah.com/tirmidhi:3747" style={{color:"#b3f4d6"}}>Hadith on the ten promised Paradise ↗</a></p><button onClick={()=>mark(selected.name)} style={{marginTop:18,padding:"13px 20px",borderRadius:12,background:"#a2e8bf",color:"#12372c",fontWeight:700}}>{read.includes(selected.name)?"✓ Marked as read · Undo":"I've read this biography ✓"}</button></article></div>}
</div></main>
}