"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "../../utils/supabase/client";
type Person={id:string;display_name:string|null;username:string|null};
type Post={id:string;body:string;user_id:string};
export default function ElmiLightAshabJourney(){
 const [open,setOpen]=useState(false),[people,setPeople]=useState<Person[]>([]),[selected,setSelected]=useState<string[]>([]),[posts,setPosts]=useState<Post[]>([]),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const handler=()=>setOpen(true);window.addEventListener("1muslim:ashab-journey",handler);return()=>window.removeEventListener("1muslim:ashab-journey",handler)},[]);
 useEffect(()=>{if(!open)return;let active=true;void(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setMessage("Sign in first to follow other members.");return}const {data,error}=await s.from("profiles").select("id,display_name,username").neq("id",user.id).limit(30);const {data:follows}=await s.from("profile_follows").select("following_id").eq("follower_id",user.id);const existing=new Set((follows||[]).map(x=>x.following_id));if(active){setPeople(((data||[]) as Person[]).filter(p=>!existing.has(p.id)).slice(0,10));if(error)setMessage(error.message)}})();return()=>{active=false}},[open]);
 const follow=async()=>{if(busy||!selected.length)return;setBusy(true);setMessage("");const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setMessage("Sign in to continue.");setBusy(false);return}let success=0;for(const id of selected){const {error}=await s.from("profile_follows").insert({follower_id:user.id,following_id:id});if(!error)success++}setMessage(`Followed ${success} of ${selected.length} members. Follow notifications depend on the recipient's notification settings.`);const {data}=await s.from("posts").select("id,body,user_id").in("user_id",selected).order("created_at",{ascending:false}).limit(8);setPosts((data||[]) as Post[]);setBusy(false);setStep(2)};
 if(!open)return null;
 return <div role="dialog" aria-modal="true" aria-label="Elmi Light Ashab Journey" style={{position:"fixed",inset:0,zIndex:10100,display:"grid",placeItems:"center",background:"rgba(0,18,14,.7)",backdropFilter:"blur(9px)",padding:16,color:"#edfff5"}}>
 <section style={{position:"relative",maxWidth:470,width:"100%",maxHeight:"85dvh",overflowY:"auto",padding:24,borderRadius:24,border:"1px solid #8dffd1",background:"linear-gradient(135deg,rgba(8,46,35,.97),rgba(11,24,35,.97))",boxShadow:"0 0 80px #48ffb43d"}}>
 <button type="button" onClick={()=>setOpen(false)} aria-label="Close" style={{position:"absolute",right:18,top:12,background:"none",border:0,color:"white",fontSize:26}}>×</button>
 <img src="/assets/hudhud-logo.PNG" alt="HudHud" width={64} height={64}/><small style={{display:"block",color:"#99ffcd",letterSpacing:2}}>✦ ELMI LIGHT · ASHAB JOURNEY</small>
 {step<2?<><h2>{step===0?"Make 10 new connections":"Confirm your follows"}</h2><p>Choose up to 10 people to follow. They can follow you back to become Ashab. No likes, messages, or comments are sent automatically.</p>
 {step===0?<>{people.map(p=><label key={p.id} style={{display:"flex",gap:10,padding:10,borderBottom:"1px solid #ffffff22"}}><input type="checkbox" checked={selected.includes(p.id)} disabled={!selected.includes(p.id)&&selected.length>=10} onChange={()=>setSelected(a=>a.includes(p.id)?a.filter(x=>x!==p.id):[...a,p.id])}/><span>{p.display_name||p.username||"Member"} <Link href={"/profile/"+p.id} style={{color:"#9dfbd5"}}>↗</Link></span></label>)}<button disabled={!selected.length} onClick={()=>setStep(1)}>Review {selected.length} follows →</button></>:<><p>You selected {selected.length} members. Confirm to follow them.</p><button onClick={()=>setStep(0)}>Back</button> <button disabled={busy} onClick={()=>void follow()}>{busy?"Following…":"Confirm follows"}</button></>}</>:<><h2>Connections sent 💚</h2><p>{message}</p><h3>Start a conversation through a post</h3>{posts.length?posts.map(p=><Link key={p.id} href={"/posts/"+p.id+"?from=ashab-journey"} style={{display:"block",padding:12,margin:"8px 0",border:"1px solid #9afac366",borderRadius:12,color:"#eafff5"}}>{p.body.slice(0,160)}<small style={{display:"block",color:"#91ffca"}}>Open post to respond →</small></Link>):<p>No posts from these members yet. You can visit their profiles.</p>}<p style={{fontSize:12}}>Post replies and recipient notifications are not yet wired on the post detail page; opening a post will not automatically send a reply.</p></>}
 {message&&step<2&&<p role="status">{message}</p>}
 <style jsx>{`button:not([aria-label]){padding:11px 16px;border:1px solid #89efc4;border-radius:12px;background:#145b45;color:white;font-weight:800;margin-top:14px;cursor:pointer}button:disabled{opacity:.5}`}</style>
 </section></div>;
}
