"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Tab="profile"|"avatar"|"header"|"live"|"shahada";
const slides=[
 {icon:"🦅",title:"Welcome to your 1Muslim profile",desc:"Your profile is your home. Discover your navigation options, then choose whether to personalize everything.",art:"🪪  ✦  ☪"},
 {icon:"🧭",title:"Your profile navigation",desc:"Profile · Avatar · Header · Live & Connections · Shahada Vault. Choose a section to see its settings.",tab:"profile" as Tab,art:"▣  ◈  ▤  ▶"},
 {icon:"✍️",title:"Your name and @handle",desc:"Google can fill in your name. Edit your display name, username, location, and bio here. Changes are saved only when you choose Save.",tab:"profile" as Tab,art:"@  ✍️  ✦"},
 {icon:"🎭",title:"Choose your avatar",desc:"Pick your avatar look and accessories. Your profile earns more customization as you gain XP.",tab:"avatar" as Tab,art:"👤  ✨  👑"},
 {icon:"🎨",title:"Make your header shine",desc:"Choose your profile header color. Elmi Light adds a soft glow to the preview.",tab:"header" as Tab,art:"🟦  🟩  ✨"},
 {icon:"🔐",title:"Your Shahada Vault",desc:"View your verification and private Shahada recording here. Your recording stays private.",tab:"shahada" as Tab,art:"☪  🛡️  ✦"},
 {icon:"🎵",title:"Connect TikTok",desc:"Optional: open TikTok authorization. This is a sandbox connection; only consider it connected after TikTok confirms authorization.",tab:"live" as Tab,link:"/tiktok",linkText:"Open TikTok connection ↗",art:"♪  ✦  📹"},
 {icon:"▶️",title:"Connect YouTube",desc:"YouTube authorization is not ready yet. Skip this step for now; we'll keep the option in Live & Connections.",tab:"live" as Tab,art:"▶  ✨  📺"},
 {icon:"⚙️",title:"Your settings, your choice",desc:"Settings includes Arabic word labels, Elmi Light effects, account deactivation, and deletion. You control these options.",link:"/settings",linkText:"Open settings ↗",art:"⚙️  💚  ✦"},
 {icon:"🌟",title:"You're ready!",desc:"Return anytime to edit your profile. Your tutorial progress is saved on this device.",art:"🦅  ✨  💚"}
];
export default function FirstProfileTour({userId,onNavigate}:{userId:string;onNavigate:(tab:Tab)=>void}){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0),[extended,setExtended]=useState(false);
 const [answers,setAnswers]=useState<Record<number,string>>({});const [focused,setFocused]=useState(false);const [hint,setHint]=useState(false);
 const key="1muslim-profile-tour-v1:"+userId;
 useEffect(()=>{try{if(localStorage.getItem(key)!=="done")setOpen(true)}catch{setOpen(true)}},[key]);
 const close=()=>{try{localStorage.setItem(key,"done")}catch{};setOpen(false)};
 const next=()=>{if(step===1&&!extended){setStep(2);return}if(step>=slides.length-1){close();return}setStep(x=>x+1)};
 const slide=slides[step];
 const choices:Record<number,string[]>={3:["Classic avatar","Explore accessories"],4:["Emerald","Ocean blue","Gold"],6:["Connect TikTok","Skip for now"],7:["Remind me later","Skip YouTube"],8:["Keep Elmi Light on","Explore settings"]};
 const options=choices[step];
 const updateAnswer=(value:string)=>{setAnswers(a=>({...a,[step]:value}));setHint(true)};
 useEffect(()=>{if(!open)return;setHint(false);setFocused(false);const timer=window.setTimeout(()=>setHint(true),2400);return()=>window.clearTimeout(timer)},[step,open]);
 const advance=()=>{setHint(false);next()};

 return <>{!open&&<button type="button" className="profileTourReplay" onClick={()=>{setStep(0);setExtended(false);setOpen(true)}}>🦅 Profile guide</button>}{open&&<div className="profileTourShade" role="dialog" aria-modal="true" aria-label="Profile welcome tutorial"><div key={step} className="profileTourCard"><div className="profileTourParticles" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i} style={{left:(i*37%97)+"%",top:(i*29%90)+"%",animationDelay:(i*.18)+"s"}}/>)}</div><div className="profileTourProgress">{step+1} / {slides.length} <button type="button" onClick={close} aria-label="Close tutorial">✕</button></div><div className="profileTourArt" aria-hidden="true"><span>{slide.icon}</span><strong>{slide.art}</strong></div><h2>{slide.title}</h2><p>{slide.desc}</p>{step===2&&<label className={"profileTourAnswer "+(focused?"isFocused":"")}>✦ Your display name (optional)<input aria-label="Try your display name" placeholder="Type your name here…" value={answers[step]||""} onFocus={()=>setFocused(true)} onBlur={()=>{setFocused(false);if(answers[step]?.trim())setHint(true)}} onChange={e=>updateAnswer(e.target.value)} /><small>Preview only. Use the profile editor to save your name.</small></label>}{options&&<div className="profileTourOptions" role="group" aria-label={"Options for "+slide.title}>{options.map((choice,i)=><button key={choice} type="button" className={answers[step]===choice?"chosen":""} onClick={()=>updateAnswer(choice)}><span>{i+1}</span>{choice}<b aria-hidden="true">{answers[step]===choice?"✓":"✦"}</b></button>)}</div>}{hint&&<div className="profileTourHint" aria-live="polite">✨ {answers[step]?"Nice choice! Tap Next to continue.":"Follow the glow. Choose an option, or tap Next to skip."} <span aria-hidden="true">↘</span></div>}{slide.tab&&<button className="profileTourPreview" type="button" onClick={()=>{onNavigate(slide.tab!);setOpen(false);try{localStorage.setItem(key,"done")}catch{}}}>Show me this section ↗</button>}{slide.link&&<Link className="profileTourPreview" href={slide.link}>{slide.linkText}</Link>}{step===1&&!extended&&<div className="profileTourChoice"><button type="button" onClick={()=>{setExtended(true);setStep(2)}}>✨ Continue full walkthrough</button><button type="button" onClick={close}>I’ll explore myself</button></div>}{(step!==1||extended)&&<div className="profileTourActions"><button type="button" onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0}>← Back</button><button type="button" onClick={advance} className={hint?"guideNext":""}>{step===slides.length-1?"Finish ✨":"Next →"}</button></div>}<button type="button" className="profileTourSkip" onClick={close}>Skip tutorial</button></div></div>}<style jsx>{`
.profileTourAnswer{display:block;text-align:left;margin:12px 0;padding:12px;border:1px solid #65e6c7;border-radius:15px;background:#0d2938;box-shadow:0 0 17px #57e6d033}.profileTourAnswer.isFocused{box-shadow:0 0 24px #6ff5e0aa,0 0 45px #568dff44}.profileTourAnswer input{display:block;width:100%;margin-top:9px;border:1px solid #66dcca;border-radius:9px;padding:13px;background:#041b27;color:white;font-size:16px;outline:none;caret-color:#8bffdd}.profileTourAnswer input:focus{border-color:#b2ffe5;box-shadow:0 0 17px #65f5d0}.profileTourAnswer small{display:block;font-size:11px;color:#a4c7c2;margin-top:8px}.profileTourOptions{display:grid;gap:9px;margin:15px 0}.profileTourOptions button{display:flex;align-items:center;gap:12px;text-align:left;padding:12px 14px;border:1px solid #5dabb8;border-radius:13px;background:#0b2b3a;color:#e6fff7;font-size:14px;transition:transform .2s,box-shadow .2s,border-color .2s;animation:optionRise .35s ease both}.profileTourOptions button:nth-child(2){animation-delay:.12s}.profileTourOptions button:nth-child(3){animation-delay:.24s}.profileTourOptions button span{display:grid;place-items:center;width:27px;height:27px;border-radius:50%;background:#27565e}.profileTourOptions button b{margin-left:auto;color:#8fffd7}.profileTourOptions button.chosen{border-color:#a4ffe5;background:#135348;box-shadow:0 0 24px #53f9cf77;transform:scale(1.02)}.profileTourHint{margin:12px auto 0;font-size:12px;color:#b4ffe5;animation:hintAppear .45s ease}.profileTourHint span{display:inline-block;animation:hintPoint .9s ease-in-out infinite}.profileTourActions button.guideNext{box-shadow:0 0 0 2px #9effe4,0 0 28px #5cf8d8;animation:nextPulse 1.7s ease-in-out infinite}@keyframes optionRise{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}@keyframes hintAppear{from{opacity:0;transform:translateY(-6px)}to{opacity:1;transform:translateY(0)}}@keyframes hintPoint{50%{transform:translate(5px,5px)}}@keyframes nextPulse{50%{box-shadow:0 0 0 3px #b0ffe5,0 0 40px #6cffe0}}.profileTourReplay{position:fixed;bottom:85px;left:14px;z-index:1300;border:1px solid #65e8c5;border-radius:999px;background:#092c2bee;color:#e8fff7;padding:10px 15px;font-weight:800;box-shadow:0 0 22px #65e8c566}
.profileTourShade{position:fixed;inset:0;z-index:3000;background:#010a15e6;backdrop-filter:blur(8px);display:grid;place-items:center;padding:16px}.profileTourCard{position:relative;isolation:isolate;overflow:hidden;width:min(470px,100%);max-height:92dvh;overflow-y:auto;padding:25px;border:1px solid #70f1d6;border-radius:26px;background:radial-gradient(circle at 50% 0,#173c56,#06171e 75%);box-shadow:0 0 65px #43c7eb55,0 0 32px #9af6c133;color:white;text-align:center}.profileTourParticles{position:absolute;inset:0;pointer-events:none;z-index:-1}.profileTourParticles i{position:absolute;width:4px;height:4px;border-radius:50%;background:#91ffe3;box-shadow:0 0 12px #59e6ff;animation:profileSpark 3.3s ease-in-out infinite}.profileTourProgress{display:flex;justify-content:space-between;align-items:center;color:#b9fbe9;font-size:12px;font-weight:800}.profileTourProgress button{background:transparent;border:0;color:white;font-size:20px}.profileTourArt{margin:18px auto;padding:25px 12px;border:1px solid #7bedd055;border-radius:20px;background:linear-gradient(135deg,#1a566055,#182e7255);display:grid;gap:12px}.profileTourArt span{font-size:55px;filter:drop-shadow(0 0 18px #81fff3);animation:profileFloat 3s ease-in-out infinite}.profileTourArt strong{font-size:23px;letter-spacing:.13em;color:#c5ffeb}.profileTourCard h2{font-size:clamp(21px,5vw,29px);margin:14px 0}.profileTourCard p{font-size:14px;line-height:1.65;color:#d1e9e5;min-height:62px}.profileTourActions,.profileTourChoice{display:flex;gap:10px;margin-top:18px}.profileTourActions button,.profileTourChoice button{flex:1;border:1px solid #78ddc5;border-radius:13px;background:#16434a;color:white;padding:13px 8px;font-size:13px;font-weight:800}.profileTourActions button:last-child,.profileTourChoice button:first-child{background:#a5f8d7;color:#052c25}.profileTourActions button:disabled{opacity:.35}.profileTourPreview{display:inline-block;border:1px solid #7af3de;border-radius:999px;color:#d3fff5;background:#0b3544;padding:9px 14px;font-size:12px;text-decoration:none}.profileTourSkip{display:block;margin:15px auto 0;border:0;background:none;color:#a6c8c6;text-decoration:underline;font-size:12px}@keyframes profileFloat{50%{transform:translateY(-8px)}}@keyframes profileSpark{50%{opacity:.25;transform:translateY(-15px)}}@media(prefers-reduced-motion:reduce){.profileTourParticles i,.profileTourArt span,.profileTourOptions button,.profileTourHint,.profileTourHint span,.profileTourActions button.guideNext{animation:none}}
`}</style></>
}
