"use client";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
type SpeechResult={results:ArrayLike<ArrayLike<{transcript:string}>>};
type Recognition={lang:string;continuous:boolean;interimResults:boolean;onresult:((e:SpeechResult)=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void};
type SpeechWindow=Window&{SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
export default function HudHudVoiceCommands(){
 const router=useRouter(),recognition=useRef<Recognition|null>(null),[enabled,setEnabled]=useState(false),[listening,setListening]=useState(false),[feedback,setFeedback]=useState("");
 const [quranVerse,setQuranVerse]=useState("");
 const [quranOptions,setQuranOptions]=useState(false);
 const [conciseNeeded,setConciseNeeded]=useState(false);
 useEffect(()=>{const h=()=>setConciseNeeded(true);window.addEventListener("1muslim:quran-concise-needed",h);return()=>window.removeEventListener("1muslim:quran-concise-needed",h)},[]);
 const [undocked,setUndocked]=useState(false),[orbPos,setOrbPos]=useState({x:0,y:0}),[tutorial,setTutorial]=useState(false);
 const moving=useRef<{x:number;y:number;ox:number;oy:number;source:"orb"|"dock";moved:boolean}|null>(null);
 const dockRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{const on=(e:Event)=>{const verse=(e as CustomEvent<{verse:string}>).detail?.verse||"";setQuranVerse(verse);setQuranOptions(false);if(verse){setUndocked(true);setOrbPos({x:Math.max(42,innerWidth-58),y:Math.max(140,innerHeight-250)})}};window.addEventListener("1muslim:quran-recorder-orb",on);return()=>window.removeEventListener("1muslim:quran-recorder-orb",on)},[]);
 useEffect(()=>{const start=()=>{if(!localStorage.getItem("1muslim:voice-drag-tutorial-seen"))setTutorial(true)};window.addEventListener("1muslim:voice-drag-tutorial",start);return()=>window.removeEventListener("1muslim:voice-drag-tutorial",start)},[]);
 const finishTutorial=()=>{setTutorial(false);try{localStorage.setItem("1muslim:voice-drag-tutorial-seen","1")}catch{}};
 const dragStart=(e:React.PointerEvent<HTMLElement>,source:"orb"|"dock")=>{if(source==="dock"&&(e.target as HTMLElement).closest("button[data-voice-toggle]"))return;moving.current={x:e.clientX,y:e.clientY,ox:orbPos.x,oy:orbPos.y,source,moved:false};e.currentTarget.setPointerCapture(e.pointerId)};
 const dragMove=(e:React.PointerEvent<HTMLElement>)=>{const d=moving.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>12)d.moved=true;if(!d.moved)return;if(d.source==="dock"&&tutorial)finishTutorial();setUndocked(true);setOrbPos({x:Math.max(34,Math.min(innerWidth-34,(d.source==="dock"?innerWidth-90:d.ox)+dx)),y:Math.max(75,Math.min(innerHeight-95,(d.source==="dock"?innerHeight-145:d.oy)+dy))})};
 const dragEnd=(e:React.PointerEvent<HTMLElement>)=>{const d=moving.current;moving.current=null;if(!d?.moved)return;const rect=dockRef.current?.getBoundingClientRect();if(rect&&e.clientX>=rect.left-45&&e.clientX<=rect.right+45&&e.clientY>=rect.top-45&&e.clientY<=rect.bottom+45)setUndocked(false)};
 useEffect(()=>{setEnabled(localStorage.getItem("1muslim:hudhud-voice")==="on")},[]);
 useEffect(()=>{if(!enabled){recognition.current?.stop();setListening(false);return}const W=window as SpeechWindow;const Constructor=W.SpeechRecognition||W.webkitSpeechRecognition;if(!Constructor){setFeedback("Voice recognition is unavailable in this browser.");return}const rec=new Constructor();recognition.current=rec;rec.lang="en-US";rec.continuous=true;rec.interimResults=false;rec.onresult=e=>{const phrase=Array.from(e.results).map(row=>row[0]?.transcript||"").join(" ").toLowerCase();const command=phrase.includes("hudhud")?phrase.slice(phrase.lastIndexOf("hudhud")+6).trim():phrase;if(/(?:go to|open|show)(?: my)? messages/.test(command)){setFeedback("Opening messages");router.push("/messages")}else if(/(?:go to|open|show)(?: my)? (?:audio rooms|rooms)/.test(command)){setFeedback("Opening audio rooms");router.push("/audio-rooms")}else if(/(?:ready to record|start recording|let.s try again)/.test(command)){window.dispatchEvent(new Event("1muslim:quran-voice-record"));setFeedback("Starting practice recorder")}else if(command.includes("stop listening")){setEnabled(false);localStorage.setItem("1muslim:hudhud-voice","off")}};rec.onerror=()=>{setListening(false);setFeedback("Microphone or speech recognition unavailable. Tap to retry.")};rec.onend=()=>setListening(false);try{rec.start();setListening(true);setFeedback("HudHud is listening")}catch{setFeedback("Tap again to allow microphone access.")}return()=>{rec.onend=null;rec.stop();recognition.current=null}},[enabled,router]);
 return <>
  <div ref={dockRef} className={"hhVoiceDock "+(tutorial?"hhVoiceTutorial":"")} onPointerDown={e=>dragStart(e,"dock")} onPointerMove={dragMove} onPointerUp={dragEnd} onPointerCancel={()=>moving.current=null} title="Drag to pull out HudHud Orb" aria-label="HudHud voice and secondary orb dock">
   <span className="hhVoiceGrip" aria-hidden="true">⠿</span><button data-voice-toggle type="button" onClick={()=>{localStorage.setItem("1muslim:hudhud-voice",enabled?"off":"on");setEnabled(!enabled)}} aria-pressed={enabled}>{listening?"🎙 Voice on":"🎙 Voice off"}</button>
  </div>
  {tutorial&&<div className="hhVoiceTutorialPrompt" role="dialog" aria-label="HudHud voice dock tutorial"><strong>✦ Discover HudHud</strong><p>Drag the highlighted Voice control to pull out your floating HudHud Orb.</p><button onClick={finishTutorial}>Got it · Skip</button></div>}
  {undocked&&quranVerse&&quranOptions&&<div role="menu" aria-label="HudHud Quran actions" style={{position:"fixed",zIndex:9402,left:Math.max(10,orbPos.x-205),top:Math.max(85,orbPos.y-175),display:"grid",gap:8,padding:10,border:"1px solid #83e8ce",borderRadius:18,background:"#0d2534ee",boxShadow:"0 12px 36px #0008"}}>{[["✦ Post","post"],["✧ Ask HudHud","chat"],["● Record","record"]].map(([label,action])=><button type="button" key={action} role="menuitem" onClick={()=>{setQuranOptions(false);window.dispatchEvent(new CustomEvent("1muslim:quran-orb-action",{detail:{action,verse:quranVerse}}))}} style={{background:"#1a4050",color:"white",border:"1px solid #76cbbb",borderRadius:11,padding:"10px 15px",textAlign:"left",cursor:"pointer"}}>{label}</button>)}</div>}
  {undocked&&<button type="button" className="hhSecondaryOrb" style={{left:orbPos.x,top:orbPos.y}} onPointerDown={e=>dragStart(e,"orb")} onPointerMove={dragMove} onPointerUp={dragEnd} onPointerCancel={()=>moving.current=null} onClick={()=>{if(!moving.current){if(conciseNeeded){window.dispatchEvent(new Event("1muslim:quran-concise"));setConciseNeeded(false);setQuranOptions(false)}else if(quranVerse)setQuranOptions(v=>!v);else window.dispatchEvent(new Event("1muslim:hudhud-vision-enable"))}}} aria-label={quranVerse?"Open or close Quran actions: Post, Chat, Record":"Movable HudHud Vision orb. Drag to the voice dock to hide."}><span className="hhSecondaryHalo"/>{quranVerse&&<span style={{position:"absolute",top:-18,fontSize:10,fontWeight:900,color:"#8fffe0",whiteSpace:"nowrap"}}>{conciseNeeded?"✦ PRESS HUDHUD":"● "+quranVerse}</span>}<img src="/assets/hudhud-logo.PNG" alt="HudHud"/></button>}
  <style jsx>{`
  .hhVoiceTutorial{z-index:9601!important;animation:hhVoiceSpotlight 1.8s ease-in-out infinite}
  .hhVoiceTutorialPrompt{position:fixed;z-index:9600;right:12px;bottom:calc(175px + env(safe-area-inset-bottom,0px));width:min(300px,calc(100vw - 24px));border:1px solid #8effd6;border-radius:18px;padding:15px;color:#effffb;background:#0b2031f5;box-shadow:0 0 0 9999px #0008,0 0 25px #74ffe577;line-height:1.45}
  .hhVoiceTutorialPrompt p{font-size:13px;margin:8px 0}.hhVoiceTutorialPrompt button{background:#80f9d9;border:0;border-radius:10px;padding:8px 12px;font-weight:700}
  @keyframes hhVoiceSpotlight{50%{box-shadow:0 0 0 7px #86ffdf55,0 0 32px #a3fff2}}
  .hhVoiceDock{position:fixed;right:10px;bottom:calc(105px + env(safe-area-inset-bottom,0px));z-index:9400;display:flex;align-items:center;gap:5px;padding:5px 8px;border:1px solid #65dfc488;border-radius:999px;background:#092331e8;box-shadow:0 0 15px #6fffe022;touch-action:none;user-select:none;color:#9afde7;cursor:grab}
  .hhVoiceDock button{border:0;background:transparent;color:#e7fff8;font-size:12px;padding:6px;touch-action:manipulation}
  .hhVoiceGrip{font-size:19px;line-height:1}
  .hhSecondaryOrb{position:fixed;z-index:9401;width:65px;height:65px;transform:translate(-50%,-50%);border-radius:50%;border:1px solid #74ffe8;background:radial-gradient(circle,#173a46,#081420);box-shadow:0 0 25px #5bf9e866;display:grid;place-items:center;touch-action:none;cursor:grab;animation:hhSecondPulse 3s ease-in-out infinite}
  .hhSecondaryOrb img{width:85%;height:85%;object-fit:contain;pointer-events:none;filter:drop-shadow(0 0 8px #9d6aff)}
  .hhSecondaryHalo{position:absolute;inset:-5px;border:2px solid transparent;border-top-color:#70ffe3;border-right-color:#b58aff;border-radius:50%;animation:hhSecondSpin 4s linear infinite;pointer-events:none}
  @keyframes hhSecondSpin{to{transform:rotate(360deg)}}@keyframes hhSecondPulse{50%{box-shadow:0 0 36px #8c73ff99;filter:brightness(1.12)}}
  @media(prefers-reduced-motion:reduce){.hhSecondaryOrb,.hhSecondaryHalo{animation:none}}
  `}</style>
 </>;
}
