"use client";
import {useEffect,useState} from "react";
import {createClient} from "../../utils/supabase/client";
export default function ModerationActions({targetType,targetId,onDeleted}:{targetType:"post"|"profile"|"comment"|"live"|"community";targetId:string;onDeleted?:()=>void}){
 const [admin,setAdmin]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{let active=true;const db=createClient();void db.rpc("is_1muslim_admin").then(({data})=>{if(active)setAdmin(data===true)});return()=>{active=false}},[]);
 const report=async()=>{const reason=window.prompt("Why are you reporting this "+targetType+"?");if(!reason)return;setBusy(true);try{const res=await fetch("/api/moderation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetType,targetId,reason})});const data=await res.json();setMessage(res.ok?"Report sent to the admin desk.":data.error||"Report failed.");}catch{setMessage("Could not send report.")}finally{setBusy(false)}};
 const remove=async()=>{if(!window.confirm("Permanently delete this "+targetType+"? This cannot be undone."))return;const confirmation=window.prompt("Type DELETE to confirm permanent removal.");if(confirmation!=="DELETE")return;setBusy(true);try{const res=await fetch("/api/moderation",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetType,targetId,confirmation})});const data=await res.json();setMessage(res.ok?"Deleted.":data.error||"Delete failed.");if(res.ok)onDeleted?.()}catch{setMessage("Delete failed.")}finally{setBusy(false)}};
 return <span style={{display:"inline-flex",gap:9,alignItems:"center",flexWrap:"wrap"}}><button type="button" disabled={busy} onClick={()=>void report()} style={{background:"transparent",border:"1px solid #7d897e",color:"inherit",borderRadius:9,padding:"7px 11px"}}>⚑ Report</button>{admin&&<button type="button" disabled={busy||!["post","profile"].includes(targetType)} onClick={()=>void remove()} style={{background:"#4a1720",border:"1px solid #b4515e",color:"#fff",borderRadius:9,padding:"7px 11px"}}>🗑 Delete</button>}{message&&<small role="status">{message}</small>}</span>
}
