"use client";
import {useEffect,useRef,useState} from "react";
import {Room,RoomEvent,Track} from "livekit-client";
type Meeting={id:string;title:string;mode:string};
type Comment={id:number;name:string;body:string;kind:string};
export default function PublicGroupMeetings(){
 const [meetings,setMeetings]=useState<Meeting[]>([]);
 const [selected,setSelected]=useState<Meeting|null>(null);
 const [room,setRoom]=useState<Room|null>(null);
 const [comments,setComments]=useState<Comment[]>([]);
 const [draft,setDraft]=useState("");
 const [canComment,setCanComment]=useState(false);
 const [error,setError]=useState("");
 const [speaker,setSpeaker]=useState("");
 const video=useRef<HTMLVideoElement>(null);
 const audio=useRef<HTMLAudioElement>(null);
 const counter=useRef(0);
 useEffect(()=>{let active=true;const load=async()=>{try{const r=await fetch("/api/public-group-meetings",{cache:"no-store"});if(r.ok){const d=await r.json();if(active){const next=(d.meetings||[]) as Meeting[];setMeetings(next);setSelected(current=>next.find(m=>m.id===current?.id)||next[0]||null)}}}catch{}};void load();const t=setInterval(()=>void load(),12000);return()=>{active=false;clearInterval(t)}},[]);
 useEffect(()=>{if(!selected)return;let disposed=false;const connection=new Room({adaptiveStream:true,dynacast:true});setRoom(connection);setComments([]);setError("");
 const sync=()=>{const participants=Array.from(connection.remoteParticipants.values());const withVideo=participants.flatMap(p=>Array.from(p.videoTrackPublications.values()).filter(x=>x.track&&x.source===Track.Source.ScreenShare).map(x=>({p,x})));const camera=participants.flatMap(p=>Array.from(p.videoTrackPublications.values()).filter(x=>x.track&&x.source===Track.Source.Camera).map(x=>({p,x})));const picked=withVideo[0]||camera[0];const track=picked?.x.track?.mediaStreamTrack;if(video.current&&track){const stream=video.current.srcObject as MediaStream|null;if(stream?.getVideoTracks()[0]!==track){video.current.srcObject=new MediaStream([track]);void video.current.play().catch(()=>{})}}if(!picked&&video.current)video.current.srcObject=null;setSpeaker(picked?.p.name||"Meeting participant");const audioTrack=participants.flatMap(p=>Array.from(p.audioTrackPublications.values()).filter(x=>x.track).map(x=>x.track!.mediaStreamTrack))[0];if(audio.current&&audioTrack){const stream=audio.current.srcObject as MediaStream|null;if(stream?.getAudioTracks()[0]!==audioTrack){audio.current.srcObject=new MediaStream([audioTrack]);void audio.current.play().catch(()=>{})}}};
 const data=(bytes:Uint8Array,p?:{name?:string})=>{try{const d=JSON.parse(new TextDecoder().decode(bytes));if(d.type==="chat"&&typeof d.body==="string"||d.type==="media"&&typeof d.body==="string"||d.type==="reaction"&&typeof d.emoji==="string"){const kind=d.type==="reaction"?"reaction":d.kind||"text";const body=d.type==="reaction"?d.emoji:d.body;if(kind!=="text"&&kind!=="reaction"&&kind!=="sticker")return;setComments(v=>[...v.slice(-29),{id:++counter.current,name:p?.name||"Member",body:body.slice(0,300),kind}])}}catch{}};
 connection.on(RoomEvent.TrackSubscribed,sync);connection.on(RoomEvent.TrackUnsubscribed,sync);connection.on(RoomEvent.ParticipantConnected,sync);connection.on(RoomEvent.ParticipantDisconnected,sync);connection.on(RoomEvent.DataReceived,data);
 void(async()=>{try{const r=await fetch("/api/public-group-meetings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"watch",callId:selected.id})});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to watch");if(disposed)return;setCanComment(d.canComment);await connection.connect(d.url,d.token);sync()}catch(e){if(!disposed)setError(e instanceof Error?e.message:"Could not connect")}})();
 return()=>{disposed=true;connection.disconnect();setRoom(null)}},[selected]);
 async function send(e:React.FormEvent){e.preventDefault();if(!room||!canComment||!draft.trim())return;const body=draft.trim().slice(0,300);try{await room.localParticipant.publishData(new TextEncoder().encode(JSON.stringify({type:"chat",body})),{reliable:true});setComments(v=>[...v.slice(-29),{id:++counter.current,name:"You",body,kind:"text"}]);setDraft("")}catch{setError("Could not send comment")}}
 if(!meetings.length)return null;
 return <section style={{margin:"20px auto",width:"100%",padding:16,border:"1px solid #398461",borderRadius:22,background:"#0d1c18",color:"#e9fff0"}}><h2 style={{margin:"0 0 8px"}}>🟢 Public Group Meetings · Live Now</h2><p style={{fontSize:13,color:"#b4d4c3"}}>Community meetings open to everyone. Sign in to join the live conversation.</p>{meetings.length>1&&<div style={{display:"flex",flexWrap:"wrap",gap:10}}>{meetings.map(m=><button key={m.id} onClick={()=>setSelected(m)} style={{padding:14,borderRadius:13,border:"1px solid #478965",background:"#214937",color:"white",cursor:"pointer"}}>🔴 {m.title} · Watch live →</button>)}</div>}{selected&&<div style={{marginTop:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><strong>🔴 {selected.title}</strong><span style={{color:"#7fe3a3",fontSize:12}}>● LIVE MEETING</span></div><div style={{position:"relative",background:"#020906",borderRadius:16,overflow:"hidden",marginTop:10}}><video ref={video} autoPlay playsInline controls style={{width:"100%",height:"min(70vw,720px)",minHeight:260,objectFit:"contain"}}/><audio ref={audio} autoPlay/><span style={{position:"absolute",top:12,left:12,background:"#132c24",padding:7,borderRadius:8,fontSize:12}}>{speaker||"Connecting…"}</span><div style={{position:"absolute",bottom:8,left:12,right:12,display:"flex",flexDirection:"column",gap:4,pointerEvents:"none"}}>{comments.slice(-5).map(c=><div key={c.id} style={{alignSelf:"flex-start",background:"#06150ddc",padding:"6px 10px",borderRadius:10,fontSize:13,maxWidth:"90%",overflowWrap:"anywhere"}}><b style={{color:"#8fe0ae"}}>{c.name}: </b>{c.body}</div>)}</div></div>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>void send(e)} style={{display:"flex",gap:8,marginTop:10}}><input aria-label="Public live comment" placeholder={canComment?"Comment live…":"Sign in to comment"} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={300} disabled={!canComment} style={{flex:1,minWidth:0,padding:12,borderRadius:12}}/><button disabled={!canComment||!draft.trim()} style={{borderRadius:12,padding:"8px 15px",background:"#6be4a2",color:"#0b2315"}}>Send</button></form></div>}</section>
}
