"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../utils/supabase/client";
import ProfileAvatar from "./ProfileAvatar";

type Story={id:string;user_id:string;body:string;media_path:string|null;media_type:"image"|"video"|null;created_at:string;expires_at:string;profile:any;media_url?:string};

export default function StoriesRail(){
  const [stories,setStories]=useState<Story[]>([]),[userId,setUserId]=useState<string|null>(null),[viewer,setViewer]=useState<Story|null>(null),[composer,setComposer]=useState(false),[body,setBody]=useState(""),[file,setFile]=useState<File|null>(null),[saving,setSaving]=useState(false);
  const load=async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();setUserId(user?.id??null);const {data}=await s.from("stories").select("id,user_id,body,media_path,media_type,created_at,expires_at,profiles(display_name,username,avatar_url,gender,avatar_gender,avatar_package,avatar_config,profile_accent)").gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(40);const rows=(data??[]) as any[];const out=await Promise.all(rows.map(async r=>{let media_url:string|undefined;if(r.media_path){const x=await s.storage.from("community-media").createSignedUrl(r.media_path,3600);media_url=x.data?.signedUrl;}return {...r,profile:r.profiles,media_url};}));setStories(out as Story[]);};
  useEffect(()=>{load()},[]);
  const grouped=useMemo(()=>{const m=new Map<string,Story>();stories.forEach(x=>{if(!m.has(x.user_id))m.set(x.user_id,x)});return [...m.values()]},[stories]);
  const publish=async()=>{if(!userId||(!body.trim()&&!file))return;setSaving(true);const s=createClient();let media_path:string|null=null,media_type:"image"|"video"|null=null;if(file){media_type=file.type.startsWith("video/")?"video":"image";media_path=userId+"/stories/"+crypto.randomUUID()+"."+(file.name.split(".").pop()||"bin");const up=await s.storage.from("community-media").upload(media_path,file,{contentType:file.type,upsert:false});if(up.error){alert(up.error.message);setSaving(false);return;}}const ins=await s.from("stories").insert({user_id:userId,body:body.trim(),media_path,media_type});if(ins.error)alert(ins.error.message);else{setBody("");setFile(null);setComposer(false);await load()}setSaving(false)};
  const Avatar=({s}:{s:Story})=><ProfileAvatar name={s.profile?.display_name||"Member"} gender={s.profile?.gender} avatarGender={s.profile?.avatar_gender} avatarPackage={s.profile?.avatar_package} avatarConfig={s.profile?.avatar_config} accent={s.profile?.profile_accent||"emerald"}/>;
  const mine=stories.find(x=>x.user_id===userId);
  return <section className="storiesSection"><div className="storiesHeader"><div><span className="eyebrow">STORIES · 24 HOURS</span><h2>Stories</h2></div><button className="storiesSee" onClick={()=>setComposer(true)}>＋ Your story</button></div><div className="storiesRail"><button className="storyAdd" onClick={()=>setComposer(true)}><span className="storyAddIcon">＋</span><strong>{mine?"Add story":"Your story"}</strong><small>{mine?"Share another update":"Photo, video or thought"}</small></button>{grouped.map(st=><button className="storyBubble" key={st.user_id} onClick={()=>{if(!userId){window.location.href="/auth?next=%2F";return;}setViewer(st)}}><span className="storyRing"><Avatar s={st}/></span><strong>{st.profile?.display_name||"Member"}</strong><small>@{st.profile?.username||"member"}</small></button>)}{!grouped.length&&<div className="storiesEmpty">Be the first to share something that disappears after 24 hours.</div>}</div>
  {composer&&<div className="storyModal" onMouseDown={e=>{if(e.target===e.currentTarget)setComposer(false)}}><div className="storyComposer"><button className="modalClose" onClick={()=>setComposer(false)}>×</button><span className="eyebrow">YOUR STORY</span><h2>Share for 24 hours.</h2><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={500} placeholder="What would you like to share?"/><label className="storyFile">🎥 / 📷 <span>{file?file.name:"Add a photo or video"}</span><input type="file" accept="image/*,video/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary full" disabled={saving} onClick={publish}>{saving?"Posting…":"Post story"}</button></div></div>}
  {viewer&&<div className="storyModal viewerModal" onClick={()=>setViewer(null)}><div className="storyViewer" onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setViewer(null)}>×</button><div className="storyViewerHead"><Avatar s={viewer}/><div><strong>{viewer.profile?.display_name||"Member"}</strong><small>@{viewer.profile?.username||"member"}</small></div></div>{viewer.media_url&&(viewer.media_type==="video"?<video className="storyMedia" src={viewer.media_url} controls autoPlay playsInline/>:<img className="storyMedia" src={viewer.media_url} alt="Story"/>)}{viewer.body&&<p className="storyViewerBody">{viewer.body}</p>}</div></div>}</section>;
}