"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import SiteNav from "../components/SiteNav";
import { createClient } from "../../utils/supabase/client";

type N={id:string;type:string;title:string;body:string;entity_type:string|null;entity_id:string|null;read_at:string|null;created_at:string;};

function hrefFor(n:N){if(n.entity_type==="live_stream"&&n.entity_id)return `/streaming/live/${n.entity_id}`;if(n.entity_type==="live_schedule"&&n.entity_id)return "/streaming/scheduled";if((n.entity_type==="dm_message"||n.entity_type==="message")&&n.entity_id&&/^[0-9a-f-]{36}$/i.test(n.entity_id))return "/messages?message="+encodeURIComponent(n.entity_id);if((n.entity_type==="dm_conversation"||n.entity_type==="conversation")&&n.entity_id&&/^[0-9a-f-]{36}$/i.test(n.entity_id))return "/messages?conversation="+encodeURIComponent(n.entity_id);if(n.entity_type==="featured_video_comment"&&n.entity_id&&/^[0-9a-f-]{36}$/i.test(n.entity_id))return "/?comment="+encodeURIComponent(n.entity_id)+"#featured-video-comments";return "/";}

export default function NotificationsPage(){
  const [items,setItems]=useState<N[]>([]);
  const [loading,setLoading]=useState(true);
  const [prefs,setPrefs]=useState<Record<string,boolean>>({});
  const [prefsBusy,setPrefsBusy]=useState(false);
  const categories=[["email_messages","Private messages"],["email_replies","Replies"],["email_comments","Post & recording comments"],["email_xp","XP tiers & milestones"]];
  async function savePref(key:string,value:boolean){setPrefsBusy(true);const db=createClient();const {data:{user}}=await db.auth.getUser();if(user){const {error}=await db.from("notification_preferences").upsert({user_id:user.id,[key]:value,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(!error)setPrefs(v=>({...v,[key]:value}));}setPrefsBusy(false)}
  useEffect(()=>{let active=true;const s=createClient();(async()=>{const {data:{user}}=await s.auth.getUser();if(!user){setLoading(false);return;}const {data}=await s.from("notifications").select("id,type,title,body,entity_type,entity_id,read_at,created_at").order("created_at",{ascending:false}).limit(60);if(active){setItems((data??[]) as N[]);setLoading(false);}const {data:pref}=await s.from("notification_preferences").select("email_messages,email_replies,email_comments,email_xp").eq("user_id",user.id).maybeSingle();if(active&&pref)setPrefs(pref as Record<string,boolean>);})();const channel=s.channel("my-notifications").on("postgres_changes",{event:"INSERT",schema:"public",table:"notifications"},payload=>{const n=payload.new as N;setItems(prev=>prev.some(x=>x.id===n.id)?prev:[n,...prev].slice(0,60))}).subscribe();return()=>{active=false;void s.removeChannel(channel)};},[]);
  return <main className="notificationsPage"><SiteNav/><div className="notificationsShell"><div className="notificationsHero"><span className="eyebrow">1MUSLIM · NOTIFICATIONS</span><h1>Stay in the loop.</h1><p>Messages, Lives, schedule changes and activity that matters to you.</p></div><section style={{marginTop:22,padding:18,border:"1px solid var(--line)",borderRadius:18,background:"var(--panel2)"}}><h2 style={{fontSize:19,margin:"0 0 8px"}}>🔔 Your notification controls</h2><p style={{fontSize:12,color:"var(--muted)"}}>In-app alerts appear as activity happens. Choose which updates also arrive by email.</p><div style={{display:"grid",gap:10,marginTop:14}}>{categories.map(([key,label])=><label key={key} style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,fontSize:13}}>{label}<input type="checkbox" disabled={prefsBusy} checked={prefs[key]!==false} onChange={e=>void savePref(key,e.target.checked)}/></label>)}</div></section>{loading?<div className="empty">Loading notifications…</div>:!items.length?<div className="empty">You're all caught up.</div>:<div className="notificationList">{items.map(n=><Link href={hrefFor(n)} onClick={()=>{const s=createClient();void s.from("notifications").update({read_at:new Date().toISOString()}).eq("id",n.id);}} className={"notificationRow "+(!n.read_at?"unread":"")} key={n.id}><span className="notificationIcon">{n.type==="xp_tier"?"🏆":n.type.startsWith("dm")?"💬":n.type.includes("comment")?"💚":n.type.startsWith("live")?"🔴":"🔔"}</span><span><strong>{n.title}</strong><small>{n.body}</small><em>{new Date(n.created_at).toLocaleString()}</em></span></Link>)}</div>}</div><style jsx>{`
.notificationsPage{min-height:100vh;background:var(--bg);color:var(--text)}.notificationsShell{max-width:820px;margin:auto;padding:38px 18px 90px}.notificationsHero{padding:20px 0 28px;border-bottom:1px solid var(--line)}.eyebrow{font-size:9px;letter-spacing:.16em;color:#8ca48d;font-weight:900}.notificationsHero h1{font-size:42px;letter-spacing:-.06em;margin:8px 0}.notificationsHero p{color:var(--muted);font-size:12px}.notificationList{margin-top:16px;display:grid;gap:8px}.notificationRow{display:flex;gap:13px;padding:15px;border:1px solid var(--line);border-radius:17px;background:var(--panel2);text-decoration:none;color:inherit}.notificationRow.unread{border-color:#60765c}.notificationIcon{width:34px;height:34px;border-radius:11px;background:var(--panel);display:grid;place-items:center;flex:0 0 auto}.notificationRow span:last-child{display:grid;gap:4px}.notificationRow strong{font-size:12px}.notificationRow small{font-size:11px;color:var(--muted);line-height:1.45}.notificationRow em{font-size:9px;color:#69776e;font-style:normal}.empty{margin-top:18px;padding:40px;border:1px dashed var(--line);border-radius:18px;color:var(--muted);text-align:center}
`}</style></main>;
}
