"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "../../../utils/supabase/client";
type Entry={id:string;author_id:string;body:string;content_type:string;reason:string;category:string;status:string;created_at:string;review_note:string|null};
export default function AdminControl(){
 const [authorized,setAuthorized]=useState(false),[loading,setLoading]=useState(true),[items,setItems]=useState<Entry[]>([]),[message,setMessage]=useState("");
 const load=async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setLoading(false);return}const {data,error}=await s.rpc("hudhud_admin_queue");if(error){setMessage("Admin role or moderation migration not configured.");setAuthorized(false)}else{setAuthorized(true);setItems((data||[]) as Entry[])}setLoading(false)};
 useEffect(()=>{void load()},[]);
 const review=async(id:string,status:"approved"|"rejected"|"changes_requested")=>{const note=window.prompt("Review note (optional):")||"";const {error}=await createClient().rpc("hudhud_review_submission",{p_id:id,p_status:status,p_note:note});if(error){setMessage(error.message);return}setMessage("Review recorded. Approved items are not automatically published until the publication workflow is connected.");await load()};
 return <main style={{maxWidth:1050,margin:"auto",padding:"30px 18px",color:"var(--text)"}}><Link href="/">← Home</Link><h1>🛡️ HudHud Admin Control Panel</h1><p>Restricted content review and audit history</p>{loading?<p>Checking admin permissions…</p>:!authorized?<p role="alert">Access unavailable. {message} Your account must have server-verified admin permissions.</p>:<><div style={{display:"flex",gap:12,flexWrap:"wrap",marginBottom:20}}><strong>Pending: {items.filter(x=>x.status==="pending").length}</strong><strong>Approved: {items.filter(x=>x.status==="approved").length}</strong><strong>Rejected: {items.filter(x=>x.status==="rejected").length}</strong></div>{items.length===0&&<p>No restricted submissions recorded yet.</p>}{items.map(x=><article key={x.id} style={{border:"1px solid var(--line)",borderRadius:14,padding:18,marginBottom:12,background:"var(--panel)"}}><small>{new Date(x.created_at).toLocaleString()} · {x.content_type} · {x.category} · {x.status}</small><p style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{x.body}</p><p><b>HudHud:</b> {x.reason}</p><small>Author: {x.author_id}</small>{x.review_note&&<p>Review note: {x.review_note}</p>}{x.status==="pending"&&<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}><button onClick={()=>void review(x.id,"approved")}>✓ Approve</button><button onClick={()=>void review(x.id,"changes_requested")}>✎ Request changes</button><button onClick={()=>void review(x.id,"rejected")}>✕ Reject</button></div>}</article>)}</>}{message&&<p role="status">{message}</p>}</main>
}