import Link from "next/link";
import SiteNav from "../components/SiteNav";

const styles={main:{minHeight:"100vh",background:"radial-gradient(ellipse at 80% 0%,#163b2b,#07110d 55%)",color:"#e8f4eb"},wrap:{maxWidth:880,margin:"0 auto",padding:"52px 22px 100px"},card:{background:"rgba(9,23,17,.94)",border:"1px solid #315340",borderRadius:24,padding:"clamp(22px,5vw,54px)",boxShadow:"0 25px 65px #0004"},eyebrow:{fontSize:11,letterSpacing:3,color:"#83dba7",fontWeight:800 as const},heading:{fontSize:"clamp(34px,6vw,56px)",margin:"15px 0 8px"},section:{marginTop:30,lineHeight:1.85,color:"#b7cbbb"},link:{color:"#9de8b6"}};
export const metadata={title:"Privacy Policy | 1Muslim",description:"How 1Muslim handles account, community, streaming and usage data."};
export default function PrivacyPage(){return <main style={styles.main}><SiteNav/><div style={styles.wrap}><article style={styles.card}><span style={styles.eyebrow}>1MUSLIM / TRUST & SAFETY</span><h1 style={styles.heading}>Privacy Policy</h1><p>Last updated: October 8, 2026</p><p>This policy describes how 1Muslim handles information when you use our website, profiles, learning tools, posts, messaging and livestream features. It is intended to be clear about the platform's current functionality; integrations and practices may change as features develop.</p>
<section style={styles.section}><h2>1. Information we collect</h2><p>We may process your account identifier, email address and sign-in information from your authentication provider; profile details you choose to provide (such as display name, username, avatar preferences, bio and location); content you submit (posts, messages, comments, media, reactions and reports); and information needed to operate livestreams, badges, XP and account settings. If you submit Shahada verification audio, that recording may be stored in a restricted-access vault for verification. Do not upload information you do not want us to process.</p></section>
<section style={styles.section}><h2>2. How information is used</h2><p>We use information to authenticate members, display profiles and content, deliver messaging and livestream features, manage moderation and safety reports, provide rewards and learning tools, troubleshoot issues and improve the service. Some optional features may involve AI-assisted review or translation; automated results may be imperfect and should not be treated as final religious guidance.</p></section>
<section style={styles.section}><h2>3. What other people can see</h2><p>Public profiles, posts, comments, livestreams and community interactions may be visible to other visitors, including visitors without accounts where the interface permits. Messages are intended for their participants, subject to safety reporting, technical processing and applicable law. Verification audio is not intended to appear on public profiles. Avoid posting private details in public areas.</p></section>
<section style={styles.section}><h2>4. Service providers and analytics</h2><p>We use third-party infrastructure for authentication, databases, hosting, storage and related platform services. The website also loads Google Analytics, which may collect device, browser and usage information using cookies or similar technologies. Third-party services process data under their own applicable terms and policies. We do not represent that all activity is end-to-end encrypted.</p></section>
<section style={styles.section}><h2>5. Storage, security and retention</h2><p>We use technical and organizational safeguards, but no online system can guarantee absolute security. Information may remain while your account is active or as reasonably necessary for operation, safety, legal obligations and backups. Deleted content may take time to disappear from backups or other users' copies. Some experimental features may store drafts or preferences in your browser rather than syncing them across devices.</p></section>
<section style={styles.section}><h2>6. Your choices</h2><p>You can edit certain profile information and may request account deletion using available account settings. You may control browser permissions and certain device or cookie settings. If a deletion, access or correction request cannot be completed through the interface, contact the platform operator through an official support channel once published.</p></section>
<section style={styles.section}><h2>7. Children and sensitive information</h2><p>Do not submit another person's private information without appropriate authorization. Parents and guardians should supervise minors' use of community and livestream features. We may restrict accounts or content to protect members and comply with law.</p></section>
<section style={styles.section}><h2>8. Updates and questions</h2><p>We may update this policy as the service changes and will update the date above. A verified privacy contact and business mailing address should be published before broad public launch. This page does not claim that an unverified contact channel exists.</p></section>
<p style={{marginTop:40}}><Link style={styles.link} href="/terms">Read Terms of Service →</Link></p></article></div></main>}