"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../utils/supabase/client";
type Entry={id:string;body:string;sender_id:string;created_at:string};
export default function LiveLightOverlay({streamId}:{streamId:string}){
 const db=useMemo(()=>createClient(),[]);
 const [messages,setMessages]=useState<Entry[]>([]);
 const [enabled,setEnabled]=useState(true);
 const [lights,setLights]=useState(true);
 const [active,setActive]=useState<Entry[]>([]);
 useEffect(()=>{const sync=()=>{try{setLights(localStorage.getItem("1muslim-elmi-light")!=="off")}catch{setLights(true)}};sync();window.addEventListener("1muslim-elmi-light-updated",sync);return()=>window.removeEventListener("1muslim-elmi-light-updated",sync)},[]);
 useEffect(()=>{let alive=true;void db.from("live_chat_messages").select("id,body,sender_id,created_at").eq("stream_id",streamId).order("created_at",{ascending:false}).limit(80).then(({data})=>{if(alive)setMessages((data||[]).reverse())});const channel=db.channel("elmi-light-overlay-"+streamId).on("postgres_changes",{event:"INSERT",schema:"public",table:"live_chat_messages",filter:"stream_id=eq."+streamId},payload=>{const m=payload.new as Entry;setMessages(prev=>prev.some(x=>x.id===m.id)?prev:[...prev.slice(-79),m]);setActive(prev=>[...prev.slice(-2),m]);window.setTimeout(()=>setActive(prev=>prev.filter(x=>x.id!==m.id)),5000)}).subscribe();return()=>{alive=false;void db.removeChannel(channel)}},[db,streamId]);
 return <div className="elmi-live-shell"><div className="elmi-live-cards" aria-live="off">{enabled&&active.map(m=><div className={"elmi-live-card "+(lights?"lit":"")} key={m.id}>{lights&&<div className="elmi-live-particles" aria-hidden="true">{Array.from({length:10},(_,i)=><i key={i} style={{left:(i*37%100)+"%",animationDelay:(i*110)+"ms"}}/>)}</div>}<span>✦ LIVE · COMMUNITY</span><strong>{m.body}</strong></div>)}</div><button type="button" className="elmi-live-toggle" onClick={()=>setEnabled(v=>!v)} aria-label={enabled?"Hide live comment effects":"Show live comment effects"}>{enabled?"✨ Comments on":"○ Comments off"}</button><style jsx>{`
 .elmi-live-shell{position:absolute;inset:0;pointer-events:none;z-index:4;color:#fff}.elmi-live-cards{position:absolute;left:12px;bottom:64px;width:min(76%,420px);display:grid;gap:8px}.elmi-live-card{position:relative;isolation:isolate;overflow:hidden;display:grid;gap:5px;padding:10px 13px;background:linear-gradient(110deg,#061e2ce8,#142d34dd,#122c20dd);border:1px solid #7bc5d9aa;border-radius:15px;backdrop-filter:blur(12px);box-shadow:0 8px 22px #0009;animation:livePop .42s ease-out both}.elmi-live-card.lit{box-shadow:0 0 25px #58dfff66,inset 0 0 16px #f6d38e22;border-color:#b5f8e8}.elmi-live-card span{position:relative;z-index:2;color:#b0f4d8;font-size:9px;letter-spacing:.12em;font-weight:900}.elmi-live-card strong{position:relative;z-index:2;font-size:clamp(11px,1.5vw,15px);line-height:1.45;overflow-wrap:anywhere}.elmi-live-particles{position:absolute;inset:0}.elmi-live-particles i{position:absolute;bottom:0;width:3px;height:3px;border-radius:50%;background:#ffdb96;box-shadow:0 0 9px 3px #7ce8ff88;animation:liveSpark 1.7s ease-out infinite}.elmi-live-particles i:nth-child(3n){background:#7dffad}.elmi-live-particles i:nth-child(3n + 1){background:#7bdfff}.elmi-live-toggle{position:absolute;right:12px;bottom:14px;pointer-events:auto;background:#0a1e2dd9;color:#d9fff1;border:1px solid #89ead488;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:800;cursor:pointer}@keyframes livePop{from{opacity:0;transform:translateY(20px) scale(.96);filter:blur(3px)}to{opacity:1;transform:translateY(0) scale(1);filter:blur(0)}}@keyframes liveSpark{from{opacity:0;transform:translateY(0)}20%{opacity:1}to{opacity:0;transform:translateY(-65px)}}@media(prefers-reduced-motion:reduce){.elmi-live-card,.elmi-live-particles i{animation:none}}
 `}</style></div>
}