"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {createClient} from "../utils/supabase/client";
type Entry={id:string;body:string;at_seconds:number;user_id:string};
type Player={getCurrentTime:()=>number;getPlayerState:()=>number;destroy:()=>void};
type YoutubeAPI={Player:new(element:HTMLElement,options:{videoId:string;playerVars:Record<string,number>;events:{onReady:()=>void}})=>Player};
declare global {interface Window {YT?:YoutubeAPI;onYouTubeIframeAPIReady?:()=>void}}
export default function TimedVideoPlayer({videoId,title,compact=false}:{videoId:string;title:string;compact?:boolean}){

 const holder=useRef<HTMLDivElement>(null),player=useRef<Player|null>(null),last=useRef(-1),shown=useRef<Set<string>>(new Set());
 const [entries,setEntries]=useState<Entry[]>([]),[active,setActive]=useState<(Entry&{until:number})[]>([]);
 const [draft,setDraft]=useState(""),[seconds,setSeconds]=useState(0),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(false),[enabled,setEnabled]=useState(true),[error,setError]=useState("");
 const videoKey=videoId;
 const watchUrl="/video-of-the-day?video="+encodeURIComponent(videoId);
 useEffect(()=>{let alive=true;const db=createClient();void db.auth.getUser().then(({data})=>{if(alive)setSignedIn(!!data.user)});
 const load=async()=>{const {data}=await db.from("featured_video_timed_comments").select("id,body,at_seconds,user_id").eq("video_key",videoKey).order("at_seconds",{ascending:true}).limit(500);if(alive&&data)setEntries(data as Entry[])};
 void load();const timer=setInterval(()=>void load(),15000);return()=>{alive=false;clearInterval(timer)}},[videoKey]);
 useEffect(()=>{shown.current.clear();last.current=-1;setActive([]);setSeconds(0);let cancelled=false;let timer:ReturnType<typeof setInterval>|undefined;
 const initialize=()=>{if(cancelled||!holder.current||!window.YT)return;const mount=document.createElement("div");holder.current.replaceChildren(mount);player.current=new window.YT.Player(mount,{videoId,playerVars:{autoplay:1,mute:1,playsinline:1,rel:0,origin:window.location.origin},events:{onReady:()=>{}}});timer=setInterval(()=>{const p=player.current;if(!p)return;const t=Math.max(0,Math.floor(p.getCurrentTime()||0));setSeconds(t);if(p.getPlayerState()!==1){last.current=t;return}if(last.current>=0&&Math.abs(t-last.current)>3)shown.current.clear();last.current=t},250)};
 if(window.YT?.Player)initialize();else{const prev=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{prev?.();initialize()};if(!document.querySelector('script[data-yt-iframe-api]')){const script=document.createElement("script");script.src="https://www.youtube.com/iframe_api";script.dataset.ytIframeApi="true";document.head.appendChild(script)}}
 return()=>{cancelled=true;if(timer)clearInterval(timer);try{player.current?.destroy()}catch{}player.current=null;holder.current?.replaceChildren()}},[videoId]);
 useEffect(()=>{if(!enabled)return;const now=Date.now();const current=entries.filter(c=>Math.abs(c.at_seconds-seconds)<=1&&!shown.current.has(c.id)).slice(0,4);if(current.length){current.forEach(c=>shown.current.add(c.id));setActive(v=>[...v.filter(c=>c.until>now),...current.map(c=>({...c,until:now+Math.min(2700,Math.max(1300,1000+c.body.length*22))}))].slice(-4))}},[seconds,entries,enabled]);
 useEffect(()=>{const t=setInterval(()=>setActive(v=>v.filter(c=>c.until>Date.now())),250);return()=>clearInterval(t)},[]);
 async function send(e:React.FormEvent){e.preventDefault();if(!draft.trim()||busy||!signedIn)return;setBusy(true);setError("");const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user){setSignedIn(false);setBusy(false);return}const body=draft.trim().slice(0,180);const at_seconds=Math.max(0,Math.min(86400,Math.floor(player.current?.getCurrentTime()||seconds)));const {data,error:saveError}=await db.from("featured_video_timed_comments").insert({video_key:videoKey,user_id:user.id,body,at_seconds}).select("id,body,at_seconds,user_id").single();if(saveError)setError("Couldn't post timed comment. Video comments may need database setup.");else if(data){setEntries(v=>[...v,data as Entry]);setDraft("");shown.current.add(data.id);setActive(v=>[...v.slice(-3),{...data,until:Date.now()+2200}])}setBusy(false)}
 return <div><div style={{position:"relative",aspectRatio:"16 / 9",background:"#000",borderRadius:18,overflow:"hidden"}}><div ref={holder} style={{width:"100%",height:"100%"}}/><div aria-live="off" style={{position:"absolute",left:12,bottom:12,width:"min(70%,420px)",display:"grid",gap:6,pointerEvents:"none"}}>{enabled&&active.map((c,i)=><div key={c.id} style={{padding:"7px 12px",background:"rgba(8,22,15,.66)",backdropFilter:"blur(8px)",color:"#fff",border:"1px solid #ffffff2c",borderRadius:12,fontSize:"clamp(11px,1.3vw,14px)",overflowWrap:"anywhere",animation:"timedFloat .24s ease-out",boxShadow:"0 3px 15px #0004"}}><span style={{color:"#9be7b6",fontWeight:700}}>💬 </span>{c.body}</div>)}</div></div><div style={{display:"flex",alignItems:"center",gap:12,justifyContent:"space-between",flexWrap:"wrap",marginTop:10}}><small style={{opacity:.7}}>⏱ {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")} · Comments appear at their video timestamp</small><label style={{fontSize:12}}><input type="checkbox" checked={enabled} onChange={e=>{setEnabled(e.target.checked);setActive([])}}/> Show floating comments</label></div>{compact?<Link href={watchUrl} style={{display:"inline-block",marginTop:12,padding:"12px 18px",background:"#b99c55",color:"#111",fontWeight:800,borderRadius:12,textDecoration:"none"}}>💬 Open video conversation · React & reply →</Link>:signedIn?<form onSubmit={e=>void send(e)} style={{display:"flex",gap:8,marginTop:10}}><input aria-label="Comment at this video timestamp" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={180} placeholder="React to this moment… 💚" style={{flex:1,minWidth:0,padding:12,borderRadius:12,border:"1px solid #b99c5588",background:"#102218",color:"white"}}/><button disabled={busy||!draft.trim()} style={{border:0,borderRadius:12,padding:"10px 15px",background:"#b99c55",color:"#111",fontWeight:800}}>{busy?"Posting…":"Post at "+Math.floor(seconds/60)+":"+String(seconds%60).padStart(2,"0")}</button></form>:<p style={{fontSize:12}}><Link href="/auth">Sign in</Link> to leave a comment at this moment in the video.</p>}{error&&<p role="alert" style={{color:"#ffb4a8"}}>{error}</p>}<style jsx>{`@keyframes timedFloat{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}`}</style></div>
}
