import Link from "next/link";
import SiteNav from "../components/SiteNav";

const styles={main:{minHeight:"100vh",background:"radial-gradient(ellipse at 80% 0%,#163b2b,#07110d 55%)",color:"#e8f4eb"},wrap:{maxWidth:880,margin:"0 auto",padding:"52px 22px 100px"},card:{background:"rgba(9,23,17,.94)",border:"1px solid #315340",borderRadius:24,padding:"clamp(22px,5vw,54px)",boxShadow:"0 25px 65px #0004"},eyebrow:{fontSize:11,letterSpacing:3,color:"#83dba7",fontWeight:800 as const},heading:{fontSize:"clamp(34px,6vw,56px)",margin:"15px 0 8px"},section:{marginTop:30,lineHeight:1.85,color:"#b7cbbb"},link:{color:"#9de8b6"}};
export const metadata={title:"Terms of Service | 1Muslim",description:"Rules for using the 1Muslim community and platform."};
export default function TermsPage(){return <main style={styles.main}><SiteNav/><div style={styles.wrap}><article style={styles.card}><span style={styles.eyebrow}>1MUSLIM / COMMUNITY STANDARDS</span><h1 style={styles.heading}>Terms of Service</h1><p>Last updated: October 8, 2026</p><p>These terms govern access to 1Muslim, a platform for Muslim community, learning, profiles, messaging, posts and livestreams. By using the service, you agree to follow these rules and applicable law. If you do not agree, do not use the service.</p>
<section style={styles.section}><h2>1. Accounts and eligibility</h2><p>Provide accurate account information, keep access credentials secure and do not impersonate others. Some participation features may require sign-in, Shahada verification, badges or additional review. Access to particular features may be limited or revoked for safety or policy reasons. Where required, minors must have parent or guardian permission.</p></section>
<section style={styles.section}><h2>2. Respectful conduct</h2><p>Do not harass, threaten, stalk, exploit, defraud or expose others' private information. Do not promote violence, hateful abuse, unlawful activity, spam or attempts to evade platform safeguards. Religious discussion and disagreement are welcome when conducted respectfully. You are responsible for your interactions and content.</p></section>
<section style={styles.section}><h2>3. Posts, videos and livestreams</h2><p>Only upload or broadcast material you have the right to share. Do not record or publish others without necessary consent. You retain ownership of your content, but grant 1Muslim a non-exclusive, worldwide license to host, process, reproduce, display and distribute it as necessary to operate and promote the service, subject to your privacy settings and applicable law. Livestreams may be interrupted, removed or restricted, and recordings are not guaranteed to be retained.</p></section>
<section style={styles.section}><h2>4. Moderation and badges</h2><p>1Muslim may review reports, remove content, limit features, suspend accounts and take action to protect users or comply with law. Badges, XP, verification and other privileges are platform features, not guarantees of religious authority, identity or character. Badge-based moderation tools must be used responsibly and may be revoked.</p></section>
<section style={styles.section}><h2>5. Religious and educational content</h2><p>Community posts, AI translations, discussions and lessons are for information and learning. They may contain errors or differences of scholarly opinion. Do not treat user-generated or automated content as a substitute for qualified religious, medical, legal or financial advice.</p></section>
<section style={styles.section}><h2>6. Purchases and subscriptions</h2><p>If paid services become available, the applicable checkout terms will describe pricing, renewal, cancellation and any refunds. Features advertised as upcoming are not promises of availability. Do not attempt unauthorized access, payment abuse or circumvention of restrictions.</p></section>
<section style={styles.section}><h2>7. Availability and limitations</h2><p>We may change, suspend or discontinue features. The service is provided on an “as available” basis to the extent permitted by law. We do not guarantee uninterrupted access, the accuracy of user content or the preservation of every upload. Nothing in these terms excludes rights or liabilities that cannot lawfully be excluded.</p></section>
<section style={styles.section}><h2>8. Privacy and changes</h2><p>Our <Link style={styles.link} href="/privacy">Privacy Policy</Link> explains data handling. We may revise these terms and post an updated date. A verified operator identity, contact address, and applicable jurisdiction/dispute terms should be completed before broad public launch; those details are intentionally not invented here.</p></section>
<p style={{marginTop:40}}><Link style={styles.link} href="/privacy">Read Privacy Policy →</Link></p></article></div></main>}