export type Question={id:string;lesson:number;prompt:string;choices:string[];answer:number;explanation:string;source:string};
export const lessonNames=["Allah is One","The Shahadah","The Qur'an","The Five Pillars","Daily Salah","Wudu","Fasting Ramadan","Zakat and Giving","The Prophet's Life","Good Character","Dua and Remembrance","Living Your Faith"];
export const questions:Question[]=[
{id:"q1",lesson:1,prompt:"How many gods does Islam teach us to worship?",choices:["One","Two","Many","None"],answer:0,explanation:"Tawhid means Allah is One, without partners.",source:"Qur'an 112:1"},
{id:"q2",lesson:2,prompt:"What does the Shahadah affirm?",choices:["Only the importance of fasting","There is no deity worthy of worship but Allah, and Muhammad is His messenger","Prayer is optional","All prophets are gods"],answer:1,explanation:"The testimony affirms Allah's oneness and Muhammad ﷺ as His messenger.",source:"Qur'an 47:19; 48:29"},
{id:"q3",lesson:3,prompt:"What is the Qur'an in Islamic belief?",choices:["A collection of poetry by scholars","A biography written by companions","Revelation from Allah","A modern commentary"],answer:2,explanation:"Muslims believe the Qur'an is revelation from Allah.",source:"Qur'an 2:2; 26:192"},
{id:"q4",lesson:4,prompt:"Which is one of the five pillars of Islam?",choices:["Hajj for those able","Building a mosque","Learning Arabic fluently","Traveling every year"],answer:0,explanation:"Hajj is a pillar for those who are able.",source:"Sahih al-Bukhari 8"},
{id:"q5",lesson:5,prompt:"How many obligatory daily prayers are prescribed?",choices:["Three","Four","Five","Seven"],answer:2,explanation:"The five obligatory daily prayers are Fajr, Dhuhr, Asr, Maghrib and Isha.",source:"Sahih al-Bukhari 46"},
{id:"q6",lesson:6,prompt:"Which action is part of wudu before salah?",choices:["Washing the face","Sleeping","Giving a speech","Eating a meal"],answer:0,explanation:"Qur'an 5:6 includes washing the face among the steps of purification.",source:"Qur'an 5:6"},
{id:"q7",lesson:7,prompt:"During which month do Muslims observe the obligatory fast?",choices:["Muharram","Ramadan","Shawwal","Rajab"],answer:1,explanation:"Fasting Ramadan is prescribed, with exemptions and make-up provisions.",source:"Qur'an 2:183–185"},
{id:"q8",lesson:8,prompt:"What is a central purpose of zakat?",choices:["Displaying wealth","Purifying wealth and helping eligible recipients","Replacing salah","Paying for a holiday"],answer:1,explanation:"Zakat is an obligation with specified categories of recipients.",source:"Qur'an 9:60; 9:103"},
{id:"q9",lesson:9,prompt:"Where did Prophet Muhammad ﷺ migrate from Makkah?",choices:["To Jerusalem","To Ta'if","To Madinah","To Damascus"],answer:2,explanation:"The Hijrah was the migration from Makkah to Madinah.",source:"Qur'an 9:40; Seerah"},
{id:"q10",lesson:10,prompt:"Which behavior best reflects the Qur'anic command about justice?",choices:["Being fair even when it goes against yourself","Favoring friends regardless of truth","Ignoring wrongdoing","Spreading unverified rumors"],answer:0,explanation:"Believers are commanded to stand firmly for justice, even against themselves.",source:"Qur'an 4:135"},
{id:"q11",lesson:11,prompt:"Which verse invites believers to remember Allah for tranquility?",choices:["Qur'an 13:28","Qur'an 111:1","Qur'an 105:1","Qur'an 106:1"],answer:0,explanation:"Qur'an 13:28 says hearts find rest in the remembrance of Allah.",source:"Qur'an 13:28"},
{id:"q12",lesson:12,prompt:"A believer makes a mistake and regrets it. Which response best matches Qur'an 39:53?",choices:["Give up on repentance","Assume forgiveness is impossible","Return to Allah and seek forgiveness","Conceal every wrong and never change"],answer:2,explanation:"Allah calls His servants not to despair of His mercy; sincere repentance matters.",source:"Qur'an 39:53"}
];
