"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import SiteNav from "../../../components/SiteNav";
import ProfileAvatar from "../../../components/ProfileAvatar";
import { createClient } from "../../../../utils/supabase/client";

type Recording={id:string;user_id:string;title:string;category:string;video_path:string;created_at:string};
type Profile={id:string;display_name:string;username:string|null;avatar_gender:string;avatar_package:string;avatar_config:Record<string,unknown>;profile_accent:string};
type Comment={id:string;user_id:string;body:string;created_at:string};

export default function ReplayPage(){
 const params=useParams(); const [recording,setRecording]=useState<Recording|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [comments,setComments]=useState<Comment[]>([]); const [names,setNames]=useState<Record<string,string>>({}); const [liked,setLiked]=useState(false); const [likes,setLikes]=useState(0); const [views,setViews]=useState(0); const [draft,setDraft]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const supabase=createClient();
 useEffect(()=>{(async()=>{const id=String(params.id); const [r,l,v,c]=await Promise.all([
  supabase.from("live_recordings").select("id,user_id,title,category,video_path,created_at").eq("id",id).eq("visibility","public").maybeSingle(),
  supabase.from("live_recording_likes").select("user_id").eq("recording_id",id),
  supabase.from("live_recording_views").select("id").eq("recording_id",id),
  supabase.from("live_recording_comments").select("id,user_id,body,created_at").eq("recording_id",id).order("created_at",{ascending:true})
 ]); setRecording(r.data as Recording|null); setLikes((l.data||[]).length); setViews((v.data||[]).length); setComments((c.data||[]) as Comment[]);
  const {data:{user}}=await supabase.auth.getUser(); setLiked(!!user&&(l.data||[]).some(x=>x.user_id===user.id));
  if(r.data){const p=await supabase.from("profiles").select("id,display_name,username,avatar_gender,avatar_package,avatar_config,profile_accent").eq("id",r.data.user_id).single(); setProfile(p.data as Profile|null); if(user){const key="onemuslim-view-"+id;if(!localStorage.getItem(key)){await supabase.from("live_recording_views").insert({recording_id:id,user_id:user.id,viewer_key:user.id});localStorage.setItem(key,"1");setViews(x=>x+1)}}}
  setLoading(false);
 })().catch(e=>{setError(e instanceof Error?e.message:"Could not load replay.");setLoading(false)})},[params.id]);
 useEffect(()=>{if(!comments.length)return;(async()=>{const ids=Array.from(new Set(comments.map(c=>c.user_id)));const {data}=await supabase.from("profiles").select("id,display_name").in("id",ids);setNames(Object.fromEntries((data||[]).map(x=>[x.id,x.display_name])));})()},[comments.length]);
 const toggleLike=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/auth";return}const id=String(params.id);if(liked){await supabase.from("live_recording_likes").delete().eq("recording_id",id).eq("user_id",user.id);setLiked(false);setLikes(x=>Math.max(0,x-1))}else{const {error:e}=await supabase.from("live_recording_likes").insert({recording_id:id,user_id:user.id});if(!e){setLiked(true);setLikes(x=>x+1)}}};
 const addComment=async(e:React.FormEvent)=>{e.preventDefault();const body=draft.trim();if(!body)return;const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/auth";return}const id=String(params.id);const {data,error:commentError}=await supabase.from("live_recording_comments").insert({recording_id:id,user_id:user.id,body}).select("id,user_id,body,created_at").single();if(commentError){setError(commentError.message);return}setComments(x=>x.concat(data as Comment));setDraft("")};
 if(loading)return <main><SiteNav/><div className="replayShell">Loading replay…</div></main>;
 if(!recording)return <main><SiteNav/><div className="replayShell"><section className="missing"><h1>This replay is unavailable.</h1><Link href="/streaming">Back to Streaming →</Link></section></div></main>;
 const videoUrl=supabase.storage.from("live-recordings").getPublicUrl(recording.video_path).data.publicUrl;
 return <main><SiteNav/><div className="replayShell"><span className="eyebrow">1MUSLIM LIVE ARCHIVE</span><h1>{recording.title||"Untitled Live"}</h1><p className="sub">{recording.category} · {new Date(recording.created_at).toLocaleString()}</p>
  <div className="replayLayout"><section><div className="videoFrame"><video src={videoUrl} controls playsInline/></div><div className="replayMeta"><div className="host"><ProfileAvatar name={profile?.display_name||"Member"} gender="" avatarGender={profile?.avatar_gender} avatarPackage={profile?.avatar_package} avatarConfig={profile?.avatar_config||{}} accent={profile?.profile_accent||"green"} size="sm"/><div><strong>{profile?.display_name||"OneMuslim member"}</strong><small>@{profile?.username||"member"}</small></div></div><div className="stats"><span>👁 {views}</span><button onClick={()=>void toggleLike()} className={liked?"liked":""}>♥ {likes}</button></div></div><Link className="back" href={profile?"/profile/"+profile.id:"/find"}>← Back to {profile?.display_name||"profile"}</Link></section>
  <aside className="comments"><span className="eyebrow">CONVERSATION</span><h2>Comments</h2><div className="commentList">{comments.length===0?<p className="muted">Be the first to join the conversation.</p>:comments.map(c=><div className="comment" key={c.id}><strong>{names[c.user_id]||"Member"}</strong><p>{c.body}</p><small>{new Date(c.created_at).toLocaleString()}</small></div>)}</div><form onSubmit={addComment}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Add a comment…"/><button>Post</button></form>{error&&<p className="error">{error}</p>}</aside></div></div>
 <style jsx>{".replayShell{max-width:1180px;margin:auto;padding:32px 18px 70px}.eyebrow{font-size:9px;letter-spacing:.16em;color:#829b87;font-weight:850}.replayShell h1{font-size:clamp(32px,5vw,54px);letter-spacing:-.06em;margin:8px 0}.sub{color:#7f8b83;font-size:12px}.replayLayout{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:16px;margin-top:22px}.videoFrame{border:1px solid var(--line);border-radius:20px;overflow:hidden;background:#000}.videoFrame video{display:block;width:100%;max-height:68vh;background:#000}.replayMeta{display:flex;justify-content:space-between;align-items:center;padding:14px 2px}.host{display:flex;align-items:center;gap:10px}.host strong,.host small{display:block}.host small{color:#758179;font-size:9px}.stats{display:flex;gap:12px;align-items:center;color:#7d8981;font-size:11px}.stats button{border:1px solid var(--line);background:var(--panel2);color:var(--text);border-radius:999px;padding:8px 12px;cursor:pointer}.stats button.liked{color:#ffb5b5;border-color:#633b3b}.back{color:#aebbb1;text-decoration:none;font-size:11px}.comments{border:1px solid var(--line);border-radius:20px;background:var(--panel2);padding:16px;display:flex;flex-direction:column;min-height:420px}.comments h2{margin:5px 0 12px}.commentList{overflow:auto;max-height:55vh}.comment{border-top:1px solid var(--line);padding:11px 0}.comment strong{font-size:11px}.comment p{font-size:11px;line-height:1.45;margin:5px 0;color:#c1cbc4}.comment small{font-size:8px;color:#69756e}.muted{color:#748078;font-size:11px}.comments form{display:flex;gap:6px;margin-top:auto;padding-top:12px}.comments input{min-width:0;flex:1;border:1px solid var(--line);background:#071009;color:var(--text);border-radius:999px;padding:10px 12px;outline:none}.comments form button{border:0;background:#d6e7b8;color:#071008;border-radius:999px;padding:0 13px;font-size:10px;font-weight:850}.error{color:#ffbcbc;font-size:10px}.missing{border:1px solid var(--line);border-radius:20px;padding:50px;text-align:center}.missing a{color:#d6e7b8}@media(max-width:820px){.replayLayout{grid-template-columns:1fr}.comments{min-height:360px}.commentList{max-height:360px}}"} </style>
 </main>;
}