"use client";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import SiteNav from "../../components/SiteNav";
import ProfileAvatar from "../../components/ProfileAvatar";
import { createClient } from "../../../utils/supabase/client";
type Profile={id:string;display_name:string;username:string|null;first_name:string|null;last_name:string|null;city:string|null;state:string|null;country:string|null;gender:string|null;bio:string|null;xp_total:number;avatar_gender:string;avatar_package:string;avatar_config:Record<string,unknown>;profile_accent:string;profile_background:string};
type LiveStream={id:string;title:string;category:string;room_name:string;viewer_count:number;started_at:string};
type Recording={id:string;title:string;category:string;video_path:string;duration_seconds:number;views:number;likes:number;comments_count:number;created_at:string};
const duration=(n:number)=>Math.floor(n/60)+":"+String(n%60).padStart(2,"0");
export default function PublicProfile(){
 const params=useParams();const [p,setP]=useState<Profile|null>(null);const [live,setLive]=useState<LiveStream|null>(null);const [recordings,setRecordings]=useState<Recording[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=createClient();const id=String(params.id);const [a,b,c]=await Promise.all([s.from("profiles").select("id,display_name,username,first_name,last_name,city,state,country,gender,bio,xp_total,avatar_gender,avatar_package,avatar_config,profile_accent,profile_background").eq("id",id).single(),s.from("live_streams").select("id,title,category,room_name,viewer_count,started_at").eq("host_id",id).eq("status","live").maybeSingle(),s.from("live_recordings").select("id,title,category,video_path,duration_seconds,views,likes,comments_count,created_at").eq("user_id",id).eq("visibility","public").order("created_at",{ascending:false})]);setP(a.data as Profile|null);setLive(b.data as LiveStream|null);setRecordings((c.data||[]) as Recording[]);setLoading(false)})()},[params.id]);
 const filtered=useMemo(()=>recordings.filter(r=>(r.title+" "+r.category).toLowerCase().includes(query.toLowerCase())),[recordings,query]);
 const url=(p:string)=>createClient().storage.from("live-recordings").getPublicUrl(p).data.publicUrl;
 if(loading)return <main><SiteNav compact/><section className="profileEmpty"><p>Loading…</p></section></main>;
 if(!p)return <main><SiteNav compact/><section className="profileEmpty"><h1>Profile not found.</h1><Link href="/find" className="primary">Back to Find</Link></section></main>;
 return <main className="profilePage"><SiteNav/><div className="profileShell"><header className={"profileHero header-"+p.profile_accent}><div className="profileHeroTop"><ProfileAvatar name={p.display_name} gender={p.gender} avatarGender={p.avatar_gender} avatarPackage={p.avatar_package} avatarConfig={p.avatar_config} accent={p.profile_accent} size="lg"/><div><span className="eyebrow">ONE MUSLIM MEMBER</span><h1>{p.display_name}</h1><p>@{p.username||"member"} · {p.xp_total.toLocaleString()} XP</p></div></div></header>
 {live&&<section className="profileLive"><div><span>● LIVE NOW</span><h2>{live.title}</h2><small>{live.category} · 👥 {live.viewer_count||0} watching</small></div><Link href={"/streaming/live/"+live.id}>Watch Live →</Link></section>}
 <section className="publicProfileBody"><div><span className="eyebrow">ABOUT</span><h2>{[p.first_name,p.last_name].filter(Boolean).join(" ")}</h2><p>{p.bio||"A member of the OneMuslim community."}</p></div><div className="publicFacts">{p.gender&&<span>Gender · {p.gender}</span>}{[p.city,p.state,p.country].filter(Boolean).length>0&&<span>Location · {[p.city,p.state,p.country].filter(Boolean).join(", ")}</span>}<span>Avatar · {p.avatar_package}</span></div></section>
 <section className="pastLives"><div className="pastHead"><div><span className="eyebrow">LIVE ARCHIVE</span><h2>Past Lives</h2><p>Public Live Studio sessions from {p.display_name}.</p></div>{recordings.length>0&&<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search past Lives…"/>}</div>
 {recordings.length===0?<div className="archiveEmpty">No public Lives have been saved yet.</div>:filtered.length===0?<div className="archiveEmpty">No Lives match “{query}”.</div>:<div className="pastGrid">{filtered.map(r=><Link className="pastCard" href={"/streaming/replay/"+r.id} key={r.id}><div className="pastThumb"><video src={url(r.video_path)} muted preload="metadata" playsInline/><span>▶</span><b>{duration(r.duration_seconds)}</b></div><div className="pastBody"><small>{r.category} · {new Date(r.created_at).toLocaleDateString()}</small><h3>{r.title||"Untitled Live"}</h3><p>👁 {r.views||0} · ♥ {r.likes||0} · 💬 {r.comments_count||0}</p></div></Link>)}</div>}
 </section><Link href="/find" className="backFind">← Back to Find</Link></div>
 <style jsx>{".profileLive{margin-top:14px;border:1px solid #5a3436;background:linear-gradient(135deg,#1b1011,#0d0909);border-radius:18px;padding:16px;display:flex;justify-content:space-between;gap:14px;align-items:center;flex-wrap:wrap}.profileLive>div>span{color:#ffb4b4;font-size:9px;font-weight:900;letter-spacing:.12em}.profileLive h2{margin:6px 0 3px;font-size:17px}.profileLive small{color:#8d7777;font-size:10px}.profileLive a{background:#e7f2d5;color:#081007;border-radius:999px;padding:10px 15px;font-size:10px;font-weight:900;text-decoration:none}.pastLives{margin-top:26px;border-top:1px solid var(--line);padding-top:26px}.pastHead{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:14px}.pastHead h2{margin:6px 0 3px;font-size:25px}.pastHead p{margin:0;color:#7d8981;font-size:11px}.pastHead input{width:min(260px,100%);border:1px solid var(--line);background:var(--panel2);color:var(--text);border-radius:999px;padding:10px 13px;font-size:11px;outline:none}.pastGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.pastCard{border:1px solid var(--line);background:var(--panel2);border-radius:16px;overflow:hidden;text-decoration:none;color:var(--text)}.pastThumb{height:155px;position:relative;background:#070b08;overflow:hidden}.pastThumb video{width:100%;height:100%;object-fit:cover}.pastThumb span{position:absolute;inset:0;display:grid;place-items:center;font-size:30px;background:linear-gradient(transparent,rgba(0,0,0,.3))}.pastThumb b{position:absolute;right:8px;bottom:8px;background:rgba(0,0,0,.75);padding:4px 6px;border-radius:5px;font-size:9px}.pastBody{padding:11px}.pastBody small{color:#76917b;font-size:8px;text-transform:uppercase;letter-spacing:.1em}.pastBody h3{font-size:14px;margin:6px 0}.pastBody p{color:#718078;font-size:9px;margin:0}.archiveEmpty{border:1px dashed var(--line);border-radius:16px;padding:30px;text-align:center;color:#7d8981;font-size:11px}@media(max-width:760px){.pastHead{align-items:stretch;flex-direction:column}.pastHead input{width:100%;box-sizing:border-box}.pastGrid{grid-template-columns:1fr}.pastThumb{height:190px}}"} </style></main>;
}