"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import SiteNav from "../../components/SiteNav";
import ProfileAvatar from "../../components/ProfileAvatar";
import { createClient } from "../../../utils/supabase/client";

type Profile={id:string;display_name:string;username:string|null;first_name:string|null;last_name:string|null;city:string|null;state:string|null;country:string|null;gender:string|null;bio:string|null;xp_total:number;avatar_gender:string;avatar_package:string;avatar_config:Record<string,unknown>;profile_accent:string;profile_background:string}; type LiveStream={id:string;title:string;category:string;room_name:string;viewer_count:number;started_at:string};

export default function PublicProfile(){
 const params=useParams();const [p,setP]=useState<Profile|null>(null);const [live,setLive]=useState<LiveStream|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const supabase=createClient(); const {data}=await supabase.from("profiles").select("id,display_name,username,first_name,last_name,city,state,country,gender,bio,xp_total,avatar_gender,avatar_package,avatar_config,profile_accent,profile_background").eq("id",String(params.id)).single(); setP(data as Profile|null); const {data:liveData}=await supabase.from("live_streams").select("id,title,category,room_name,viewer_count,started_at").eq("host_id",String(params.id)).eq("status","live").maybeSingle(); setLive(liveData as LiveStream|null); setLoading(false)})()},[params.id]);
 if(loading)return <main><SiteNav compact/><section className="profileEmpty"><p>Loading…</p></section></main>;
 if(!p)return <main><SiteNav compact/><section className="profileEmpty"><h1>Profile not found.</h1><Link href="/find" className="primary">Back to Find</Link></section></main>;
 return <main className="profilePage"><SiteNav/><div className="profileShell"><header className={`profileHero header-${p.profile_accent}`}><div className="profileHeroTop"><ProfileAvatar name={p.display_name} gender={p.gender} avatarGender={p.avatar_gender} avatarPackage={p.avatar_package} avatarConfig={p.avatar_config} accent={p.profile_accent} size="lg"/><div><span className="eyebrow">ONE MUSLIM MEMBER</span><h1>{p.display_name}</h1><p>@{p.username||"member"} · {p.xp_total.toLocaleString()} XP</p></div></div></header>{live&&<section style={{marginTop:14,border:"1px solid #5a3436",background:"linear-gradient(135deg,#1b1011,#0d0909)",borderRadius:18,padding:16,display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><span style={{color:"#ffb4b4",fontSize:9,fontWeight:900,letterSpacing:".12em"}}>● LIVE NOW</span><h2 style={{margin:"6px 0 3px",fontSize:17}}>{live.title}</h2><span style={{color:"#8d7777",fontSize:10}}>{live.category} · 👥 {live.viewer_count||0} watching</span></div><Link href={"/streaming/live/"+live.id} style={{textDecoration:"none",background:"#e7f2d5",color:"#081007",borderRadius:999,padding:"10px 15px",fontSize:10,fontWeight:900}}>Watch Live →</Link></section>}<section className="publicProfileBody"><div><span className="eyebrow">ABOUT</span><h2>{[p.first_name,p.last_name].filter(Boolean).join(" ")}</h2><p>{p.bio||"A member of the OneMuslim community."}</p></div><div className="publicFacts">{p.gender&&<span>Gender · {p.gender}</span>}{[p.city,p.state,p.country].filter(Boolean).length>0&&<span>Location · {[p.city,p.state,p.country].filter(Boolean).join(", ")}</span>}<span>Avatar · {p.avatar_package}</span></div></section><Link href="/find" className="backFind">← Back to Find</Link></div></main>;
}