"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import SiteNav from "../../components/SiteNav";
import ProfileAvatar, { tierForXp } from "../../components/ProfileAvatar";
import { createClient } from "../../../utils/supabase/client";

type Profile={id:string;display_name:string;username:string|null;first_name:string|null;last_name:string|null;city:string|null;state:string|null;country:string|null;gender:string|null;bio:string|null;xp_total:number;avatar_gender:string;avatar_package:string;avatar_config:Record<string,unknown>;profile_accent:string;profile_background:string;profile_title:string};
type LiveStream={id:string;title:string;category:string;room_name:string;viewer_count:number;started_at:string};
type Recording={id:string;title:string;category:string;video_path:string;duration_seconds:number;views:number;likes:number;comments_count:number;created_at:string};
type Post={id:string;body:string;created_at:string};
type Lesson={title:string;slug:string;completed_at:string};

const duration=(n:number)=>Math.floor(n/60)+":"+String(n%60).padStart(2,"0");

export default function PublicProfile(){
 const params=useParams();const [p,setP]=useState<Profile|null>(null);const [live,setLive]=useState<LiveStream|null>(null);const [recordings,setRecordings]=useState<Recording[]>([]);const [posts,setPosts]=useState<Post[]>([]);const [lesson,setLesson]=useState<Lesson|null>(null);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [videoUrls,setVideoUrls]=useState<Record<string,string>>({});
 useEffect(()=>{(async()=>{const s=createClient();const id=String(params.id);
 const [a,b,c,d,e]=await Promise.all([
  s.from("profiles").select("id,display_name,username,first_name,last_name,city,state,country,gender,bio,xp_total,avatar_gender,avatar_package,avatar_config,profile_accent,profile_background,profile_title").eq("id",id).single(),
  s.from("live_streams").select("id,title,category,room_name,viewer_count,started_at").eq("host_id",id).eq("status","live").maybeSingle(),
  s.from("live_recordings").select("id,title,category,video_path,duration_seconds,views,likes,comments_count,created_at").eq("user_id",id).eq("visibility","public").order("created_at",{ascending:false}).limit(8),
  s.from("posts").select("id,body,created_at").eq("user_id",id).order("created_at",{ascending:false}).limit(8),
  s.from("lesson_completions").select("lesson_id,completed_at").eq("user_id",id).eq("passed",true).order("completed_at",{ascending:false}).limit(1)
 ]);
 setP(a.data as Profile|null);setLive(b.data as LiveStream|null);setRecordings((c.data||[]) as Recording[]);setPosts((d.data||[]) as Post[]);
 if(e.data?.[0]){const{data:ld}=await s.from("lessons").select("title,slug").eq("id",e.data[0].lesson_id).maybeSingle();if(ld)setLesson({title:ld.title,slug:ld.slug,completed_at:e.data[0].completed_at})}
 const map:Record<string,string>={};for(const v of(c.data||[])){const{data}=await s.storage.from("live-recordings").createSignedUrl(v.video_path,3600);if(data?.signedUrl)map[v.id]=data.signedUrl}setVideoUrls(map);setLoading(false)})()},[params.id]);
 useEffect(()=>{let active=true; const poll=async()=>{const s=createClient(); const {data}=await s.from("live_streams").select("id,title,category,room_name,viewer_count,started_at").eq("host_id",String(params.id)).eq("status","live").maybeSingle(); if(active)setLive(data as LiveStream|null)}; void poll(); const timer=window.setInterval(()=>void poll(),5000); return()=>{active=false;window.clearInterval(timer)}},[params.id]);
 const filtered=useMemo(()=>recordings.filter(r=>(r.title+" "+r.category).toLowerCase().includes(query.toLowerCase())),[recordings,query]);
 const tier=useMemo(()=>tierForXp(p?.xp_total??0),[p?.xp_total]);
 if(loading)return <main><SiteNav compact/><section className="profileEmpty"><p>Loading…</p></section></main>;
 if(!p)return <main><SiteNav compact/><section className="profileEmpty"><h1>Profile not found.</h1><Link href="/find" className="primary">Back to Find</Link></section></main>;
 const location=[p.city,p.state,p.country].filter(Boolean).join(", ");
 return <main className="publicProfile"><SiteNav/><div className="profileShell">
 <header className={"profileHero header-"+p.profile_accent}><div className="profileHeroTop"><ProfileAvatar name={p.display_name} gender={p.gender} avatarGender={p.avatar_gender} avatarPackage={p.avatar_package} avatarConfig={p.avatar_config} accent={p.profile_accent} size="lg"/><div><span className="eyebrow">{p.profile_title||"ONE MUSLIM MEMBER"} · {tier.icon} {tier.name}</span><h1>{p.display_name}</h1><p>@{p.username||"member"} · {p.xp_total.toLocaleString()} XP</p></div></div><p className="publicBio">{p.bio||"Building a life of faith, learning and community."}</p><div className="publicPills">{location&&<span>📍 {location}</span>}<span>🎨 {p.profile_accent} header</span><span>✦ {p.avatar_package}</span></div></header>
 {live&&<section className="profileLive"><div><span>● LIVE NOW</span><h2>{live.title}</h2><small>{live.category} · 👥 {live.viewer_count||0} watching</small></div><Link href={"/streaming/live/"+live.id}>Watch Live Now →</Link></section>}
 <div className="publicProfileGrid"><div>
 <section className="publicSection"><div className="sectionHead"><div><span className="eyebrow">VIDEO</span><h2>Videos</h2></div><Link href="/streaming/library">See all →</Link></div>{recordings.length===0?<p className="muted">No public videos yet.</p>:<div className="pastGrid">{filtered.slice(0,4).map(r=><Link className="pastCard" href={"/streaming/replay/"+r.id} key={r.id}><div className="pastThumb">{videoUrls[r.id]&&<video src={videoUrls[r.id]} muted preload="metadata" playsInline/>}<span>▶</span><b>{duration(r.duration_seconds)}</b></div><div className="pastBody"><small>{r.category} · {new Date(r.created_at).toLocaleDateString()}</small><h3>{r.title||"Untitled Video"}</h3><p>👁 {r.views||0} · ♥ {r.likes||0} · 💬 {r.comments_count||0}</p></div></Link>)}</div>}</section>
 <section className="publicSection"><div className="sectionHead"><div><span className="eyebrow">POSTS</span><h2>Posts</h2></div><Link href="/community">Community →</Link></div>{posts.length?posts.map(x=><article className="postItem" key={x.id}><small>{new Date(x.created_at).toLocaleDateString()}</small><p>{x.body||"Video post"}</p></article>):<p className="muted">No posts yet.</p>}</section>
 </div><aside>
 <section className="publicSection"><span className="eyebrow">JOURNEY</span><h2>Learning Journey</h2>{lesson?<div className="journeyItem"><strong>{lesson.title}</strong><span>✓ Completed {new Date(lesson.completed_at).toLocaleDateString()}</span></div>:<p className="muted">Their completed lessons will appear here.</p>}</section>
 <section className="publicSection"><span className="eyebrow">LAST LIVE</span>{live?<><h2>{live.title}</h2><p className="muted">Currently live · {live.category}</p><Link className="watchButton" href={"/streaming/live/"+live.id}>Watch Now →</Link></>:recordings[0]?<><h2>{recordings[0].title}</h2><p className="muted">Latest saved Live · {recordings[0].category}</p><Link className="watchButton" href={"/streaming/replay/"+recordings[0].id}>Watch Now →</Link></>:<p className="muted">No Live recording yet.</p>}</section>
 <section className="publicSection"><span className="eyebrow">PROFILE CUSTOMIZATION</span><h2>Built by them.</h2><p className="muted">This profile carries their Edit Profile choices — avatar package, accessories, header color, title, identity and bio.</p></section>
 </aside></div><Link href="/find" className="backFind">← Back to Find</Link></div>
 <style jsx>{".publicBio{max-width:680px;color:#aab4ad;line-height:1.7;font-size:13px;margin:18px 0 0}.publicPills{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.publicPills span{border:1px solid #2b382f;background:#0b120d;border-radius:999px;padding:7px 10px;font-size:9px;color:#aeb9b1}.publicProfileGrid{display:grid;grid-template-columns:1.35fr .65fr;gap:14px;margin-top:14px}.publicSection{border:1px solid var(--line);background:var(--panel2);border-radius:18px;padding:18px;margin-bottom:14px}.publicSection h2{font-size:20px;margin:5px 0 12px}.sectionHead{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.sectionHead a{font-size:10px;color:#b9c9be}.pastGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.pastCard{border:1px solid var(--line);background:#0b120d;border-radius:14px;overflow:hidden;text-decoration:none;color:var(--text)}.pastThumb{height:130px;position:relative;background:#070b08;overflow:hidden}.pastThumb video{width:100%;height:100%;object-fit:cover}.pastThumb span{position:absolute;inset:0;display:grid;place-items:center;font-size:28px;background:linear-gradient(transparent,rgba(0,0,0,.25))}.pastThumb b{position:absolute;right:7px;bottom:7px;background:rgba(0,0,0,.75);padding:4px 6px;border-radius:5px;font-size:8px}.pastBody{padding:10px}.pastBody small{color:#76917b;font-size:8px;text-transform:uppercase}.pastBody h3{font-size:12px;margin:5px 0}.pastBody p{color:#718078;font-size:8px;margin:0}.postItem{padding:10px 0;border-bottom:1px solid #1b251e}.postItem:last-child{border-bottom:0}.postItem small{color:#718078;font-size:9px}.postItem p{color:#aab4ad;font-size:12px;line-height:1.6;margin:5px 0}.journeyItem{display:grid;gap:5px}.journeyItem strong{font-size:13px}.journeyItem span{font-size:10px;color:#7c8b82}.watchButton{display:inline-flex;margin-top:8px;padding:9px 13px;border-radius:999px;background:#d6e7b8;color:#071008;text-decoration:none;font-size:10px;font-weight:850}.profileLive{margin-top:14px;border:1px solid #5a3436;background:linear-gradient(135deg,#1b1011,#0d0909);border-radius:18px;padding:16px;display:flex;justify-content:space-between;gap:14px;align-items:center;flex-wrap:wrap}.profileLive>div>span{color:#ffb4b4;font-size:9px;font-weight:900;letter-spacing:.12em}.profileLive h2{margin:6px 0 3px;font-size:17px}.profileLive small{color:#8d7777;font-size:10px}.profileLive a{background:#e7f2d5;color:#081007;border-radius:999px;padding:10px 15px;font-size:10px;font-weight:900;text-decoration:none}@media(max-width:760px){.publicProfileGrid{grid-template-columns:1fr}.pastGrid{grid-template-columns:1fr}.pastThumb{height:180px}}"} </style></main>;
}