"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import SiteNav from "../components/SiteNav";
import {createClient} from "../../utils/supabase/client";
const letters=[["ا","Alif"],["ب","Bā"],["ت","Tā"],["ث","Thā"],["ج","Jīm"],["ح","Ḥā"],["خ","Khā"],["د","Dāl"],["ذ","Dhāl"],["ر","Rā"],["ز","Zāy"],["س","Sīn"],["ش","Shīn"],["ص","Ṣād"],["ض","Ḍād"],["ط","Ṭā"],["ظ","Ẓā"],["ع","ʿAyn"],["غ","Ghayn"],["ف","Fā"],["ق","Qāf"],["ك","Kāf"],["ل","Lām"],["م","Mīm"],["ن","Nūn"],["ه","Hā"],["و","Wāw"],["ي","Yā"]];
const starterWords=[{"ar":"باب","roman":"bāb","en":"door","letters":["ب","ا"]},{"ar":"أب","roman":"ab","en":"father","letters":["ا","ب"]},{"ar":"أم","roman":"umm","en":"mother","letters":["ا","م"]},{"ar":"بيت","roman":"bayt","en":"house","letters":["ب","ي","ت"]},{"ar":"يد","roman":"yad","en":"hand","letters":["ي","د"]},{"ar":"نور","roman":"nūr","en":"light","letters":["ن","و","ر"]},{"ar":"قلم","roman":"qalam","en":"pen","letters":["ق","ل","م"]},{"ar":"كتاب","roman":"kitāb","en":"book","letters":["ك","ت","ا","ب"]},{"ar":"سلام","roman":"salām","en":"peace","letters":["س","ل","ا","م"]}];
export default function ArabicBadgesPage(){
 const [userId,setUserId]=useState<string|null>(null),[speaks,setSpeaks]=useState(false),[done,setDone]=useState<string[]>([]),[message,setMessage]=useState(""),[ready,setReady]=useState(false);
 useEffect(()=>{let active=true;const db=createClient();void(async()=>{const {data:{user}}=await db.auth.getUser();if(!active)return;setUserId(user?.id||null);if(user){const {data}=await db.from("arabic_learning_progress").select("speaks_arabic,letters_completed").eq("user_id",user.id).maybeSingle();if(active&&data){setSpeaks(!!data.speaks_arabic);setDone(Array.isArray(data.letters_completed)?data.letters_completed:[])}}if(active)setReady(true)})();return()=>{active=false}},[]);
 const [selected,setSelected]=useState("ب");
 const [soundStatus,setSoundStatus]=useState("");
 const speak=(text:string)=>{if(!("speechSynthesis" in window)){setSoundStatus("Audio unavailable. A teacher-recorded Arabic sound pack is recommended.");return}const voice=new SpeechSynthesisUtterance(text);voice.lang="ar-SA";voice.rate=0.65;window.speechSynthesis.cancel();window.speechSynthesis.speak(voice);setSoundStatus("Device-generated pronunciation preview; not a verified reciter recording.")};
 const unlocked=starterWords.filter(word=>word.letters.every(letter=>done.includes(letter)));
 const save=async(nextSpeaks:boolean,nextDone:string[])=>{if(!userId)return;const db=createClient();const {error}=await db.from("arabic_learning_progress").upsert({user_id:userId,speaks_arabic:nextSpeaks,letters_completed:nextDone,updated_at:new Date().toISOString()},{onConflict:"user_id"});setMessage(error?"Could not save. The Arabic progress database migration may need to be applied.":"Progress saved ✓")};
 return <><SiteNav/><main style={{minHeight:"100vh",background:"#080f1c",color:"#f1fff9",padding:"110px 16px 100px"}}><div style={{maxWidth:760,margin:"auto"}}>
 <Link href="/profile" style={{color:"#a7f7df"}}>← Profile</Link><p style={{color:"#90ebd6",marginTop:22}}>🌀 HUDHUD · ARABIC LEARNING</p><h1 style={{fontSize:34,fontWeight:800}}>Earn your Arabic badges</h1><p style={{color:"#c3d8da",margin:"12px 0 25px"}}>Learn the Arabic letters, build your pronunciation, and progress toward language proficiency.</p>
 <section style={{padding:18,border:"1px solid #42776d",borderRadius:18,background:"#10232d"}}><h2>🗣️ Arabic Language Badge</h2><label style={{display:"flex",gap:12,alignItems:"center",marginTop:12}}><input type="checkbox" checked={speaks} disabled={!userId} onChange={e=>{setSpeaks(e.target.checked);void save(e.target.checked,done)}}/> Do you speak Arabic?</label><p style={{fontSize:13,color:"#c3d8da",marginTop:10}}>This is a self-reported preference, not a verified language badge. HudHud will offer a proficiency assessment later.</p></section>
 <section style={{marginTop:18,padding:18,border:"1px solid #42776d",borderRadius:18,background:"#10232d"}}><h2>🔤 Qur'an Letters Badge</h2><p style={{fontSize:13,color:"#c3d8da"}}>Mark each letter after practicing it. {done.length}/28 complete. Completing the checklist tracks your study; pronunciation verification is a future step.</p><div role="progressbar" aria-valuenow={done.length} aria-valuemin={0} aria-valuemax={28} aria-label="Arabic letters progress" style={{height:9,background:"#263b44",borderRadius:20,margin:"16px 0",overflow:"hidden"}}><div style={{height:"100%",width:`${done.length/28*100}%`,background:"#6ff1bd"}}/></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(95px,1fr))",gap:10}}>{letters.map(([letter,label])=><button key={letter} disabled={!userId} aria-pressed={done.includes(letter)} onClick={()=>setSelected(letter)} style={{padding:14,borderRadius:14,border:"1px solid #5a9283",background:done.includes(letter)?"#155744":"#182f3b",color:"white",cursor:"pointer"}}><span style={{display:"block",fontSize:30}}>{letter}</span><small>{label}</small>{done.includes(letter)&&<span style={{display:"block"}}>✓</span>}</button>)}</div>
 <section style={{marginTop:20,padding:16,border:"1px solid #488779",borderRadius:16,background:"#0a2830"}}><h3>👶 A1 · Letter Trainer</h3><p style={{fontSize:13}}>Step 1: tap a letter. Step 2: listen to its sound. Step 3: repeat it. Step 4: mark it practiced.</p><div lang="ar" style={{fontSize:62,textAlign:"center"}}>{selected}</div><p style={{textAlign:"center"}}>{letters.find(item=>item[0]===selected)?.[1]}</p><div style={{display:"flex",gap:8,justifyContent:"center",flexWrap:"wrap"}}><button onClick={()=>speak(selected)} style={{padding:12,borderRadius:12}}>🔊 Hear letter</button><button disabled={!userId} onClick={()=>{const next=done.includes(selected)?done:[...done,selected];setDone(next);void save(speaks,next)}} style={{padding:12,borderRadius:12,background:"#75e6b6",color:"#071c1c"}}>✓ I practiced this</button></div><p role="status" style={{fontSize:12,color:"#b8d7d4"}}>{soundStatus}</p><small>Practice marks are self-reported, not a pronunciation certification. Recorded native-speaker sound clips are needed for dependable teaching.</small></section>
 <section style={{marginTop:20,padding:16,border:"1px solid #488779",borderRadius:16,background:"#0a2830"}}><h3>✨ Words you can build</h3><p style={{fontSize:13}}>As you practice letters, HudHud unlocks simple words using only those letters. Vowel marks are introduced during word practice.</p>{unlocked.length?unlocked.map(word=><div key={word.ar} style={{display:"flex",alignItems:"center",gap:12,justifyContent:"space-between",borderBottom:"1px solid #35535a",padding:"12px 0"}}><div><strong lang="ar" style={{fontSize:27}}>{word.ar}</strong><p style={{fontSize:13}}>{word.roman} · {word.en}</p><small>{word.letters.join(" + ")}</small></div><button onClick={()=>speak(word.ar)} style={{padding:10,borderRadius:10}}>🔊 Sound</button></div>):<p>Start with ب and ا to unlock your first word: باب (door).</p>}</section>
 {done.length===28&&<p style={{marginTop:16,color:"#a8ffcf"}}>🌟 All 28 letters practiced! You're ready for a pronunciation review.</p>}</section>
 {!ready&&<p>Loading your learning profile…</p>}{ready&&!userId&&<p><Link href="/auth" style={{color:"#9bffda"}}>Sign in to save your progress →</Link></p>}{message&&<p role="status" style={{marginTop:16}}>{message}</p>}
 </div></main></>;
}
