import Link from "next/link";
import SiteNav from "../components/SiteNav";
import MyBadges from "../components/MyBadges";

const tiers=[
 {name:"Shahadah Badge",icon:"✦",image:"/assets/badges/shahada-badge.png",subtitle:"Join the conversation",earn:"Complete the Shahadah verification process.",features:["Watch livestreams","Create posts","Comment and react","Like and share content","Go live"],next:"Dua Badge"},
 {name:"Dua Badge",icon:"🤲",image:"/assets/badges/dua-badge.PNG",subtitle:"Help shape the community",earn:"Complete the Dua lesson and demonstrate praising Allah before making a request.",features:["Everything in Shahadah","Create communities","Vote up a livestream for wider visibility"],next:"Live Badge"},
 {name:"Live Badge",icon:"🔴",image:"",subtitle:"Become a featured creator",earn:"Complete the creator training and livestream eligibility review (criteria being finalized).",features:["Everything in Dua","Become eligible for HudHud replay selection","Have an eligible recording considered for open homepage slots","Be considered for scheduled topic programming"],next:"Community Steward Badge"},
 {name:"Community Steward Badge",icon:"🛡️",image:"",subtitle:"Protect the community",earn:"Complete safety training and administrator review.",features:["Everything in Live","Priority safety reports","Escalate serious livestream concerns to moderators"],next:"Trust Guardian Badge"},
 {name:"Trust Guardian Badge",icon:"⚖️",image:"",subtitle:"Highest trust tier",earn:"Invitation-only, after a proven trust history and supervised moderation training.",features:["Everything in Community Steward","Flag a live for urgent shutdown review","Track escalation outcomes","Priority moderator notification"],next:""}
];
export default function BadgeGuide(){
 return <main style={{minHeight:"100vh",background:"var(--bg)",color:"var(--text)"}}><SiteNav/><div style={{maxWidth:1120,margin:"auto",padding:"44px 18px 90px"}}>
 <span style={{color:"#c7b37c",fontSize:12,letterSpacing:3,fontWeight:900}}>1MUSLIM · TRAINING & ACHIEVEMENTS</span><h1 style={{fontSize:"clamp(35px,6vw,64px)",letterSpacing:"-.05em",margin:"10px 0"}}>Your Badge Journey</h1><p style={{maxWidth:740,color:"var(--muted)",lineHeight:1.8}}>Learn, contribute and grow. Each badge represents a new milestone and unlocks more ways to participate in 1Muslim.</p>
 <MyBadges />
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(265px,1fr))",gap:18,marginTop:30}}>{tiers.map((tier,i)=><article key={tier.name} style={{border:"1px solid #5b674e",borderRadius:24,padding:24,background:"linear-gradient(155deg,#1a2920,#0c1510)",color:"#eef4e9",display:"flex",flexDirection:"column",gap:13,boxShadow:"0 12px 40px #0003"}}>
 <div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><span style={{fontSize:11,letterSpacing:2,color:"#d8c58c",fontWeight:800}}>LEVEL {i+1}</span><span style={{border:"1px solid #786e4b",borderRadius:30,padding:"5px 10px",fontSize:11,color:"#e5d5a5"}}>{i===4?"Highest trust":i===3?"Safety":i===2?"Creator":"Training"}</span></div>
 <div style={{height:145,display:"grid",placeItems:"center"}}>{tier.image?<img src={tier.image} alt={tier.name} style={{height:142,maxWidth:"100%",objectFit:"contain",filter:"drop-shadow(0 8px 20px #0008)"}}/>:<span style={{fontSize:72,filter:"drop-shadow(0 6px 18px #d0aa5555)"}}>{tier.icon}</span>}</div>
 <h2 style={{margin:0,fontSize:25}}>{tier.name}</h2><p style={{color:"#d1bf8a",margin:0,fontWeight:700}}>{tier.subtitle}</p>
 <div style={{borderTop:"1px solid #334838",paddingTop:15}}><strong style={{fontSize:13}}>HOW TO EARN</strong><p style={{color:"#b9c8bc",lineHeight:1.7,fontSize:13}}>{tier.earn}</p></div>
 <div><strong style={{fontSize:13}}>WHAT IT UNLOCKS</strong><ul style={{paddingLeft:20,lineHeight:2,color:"#dce9d9",fontSize:13}}>{tier.features.map(f=><li key={f}>✓ {f}</li>)}</ul></div>
 <div style={{marginTop:"auto",borderTop:"1px solid #334838",paddingTop:15}}>{tier.next?<small style={{color:"#b8c7b8"}}>Next milestone → {tier.next}</small>:<small style={{color:"#e0c98c"}}>Eligible for HudHud's featured creator queue</small>}</div>
 </article>)}</div>
 <section style={{border:"1px solid #8c6a4c",borderRadius:22,padding:24,marginTop:25,background:"var(--panel)"}}><span className="eyebrow">TRUST GUARDIAN PRIVILEGE</span><h2>🚩 Flag to Shut Down an Ongoing Live</h2><p style={{lineHeight:1.8,color:"var(--muted)"}}>Once awarded the Trust Guardian Badge, a member can see a special <strong>Flag for Shutdown Review</strong> button on active livestreams. This sends an urgent, evidence-backed report to authorized moderators. A badge holder cannot unilaterally terminate another member's stream.</p><div style={{display:"inline-block",padding:"12px 18px",border:"1px solid #9c605a",borderRadius:12,color:"#d69c92",fontWeight:900}}>🚩 Flag for Shutdown Review · Coming soon</div><ol style={{lineHeight:2,color:"var(--muted)"}}><li>Choose a serious safety reason and provide details.</li><li>HudHud records the stream, reporter, timestamp and evidence.</li><li>An administrator or authorized moderator reviews the urgent alert.</li><li>Authorized moderators may suspend a stream, with an audit log and host appeal.</li><li>Abusive or false reports can lead to badge revocation.</li></ol></section><section style={{border:"1px solid var(--line)",borderRadius:22,padding:24,marginTop:20,background:"var(--panel)"}}><h2>🎓 Training → Badges → Trust</h2><p style={{lineHeight:1.8,color:"var(--muted)"}}>Shahadah → Dua → Live → Community Steward → Trust Guardian. Each level unlocks the previous privileges and new responsibilities. Badges are tied to verified accounts; XP alone never grants moderation authority. Sensitive privileges require review, and badges can be suspended or revoked.</p><p style={{fontSize:12,color:"var(--muted)"}}>This is the badge system roadmap. Server-side permissions, badge awards, voting, safety escalation and moderation audit trails are not active yet.</p></section><section style={{border:"1px solid #4c674e",borderRadius:22,padding:24,marginTop:25,background:"var(--panel)"}}><h2>📺 How Live Votes & HudHud Features Work</h2><p style={{lineHeight:1.8,color:"var(--muted)"}}>Dua Badge holders will be able to vote up a currently live broadcast. Votes help HudHud identify content worth highlighting, but do not guarantee placement. Live Badge holders can opt in to have approved recordings considered for vacant homepage slots and topic-matched programming. Admin review, creator consent, content safety and scheduling rules apply.</p><p style={{fontSize:12,color:"var(--muted)"}}>This page describes the planned badge privileges. The badge entitlement checks, voting system and HudHud replay scheduling must be implemented and secured before these unlocks are active.</p><Link href="/#paths" style={{display:"inline-block",marginTop:12,padding:"12px 20px",borderRadius:12,background:"#dbe9c4",color:"#112016",fontWeight:800,textDecoration:"none"}}>Start training →</Link></section>
 </div></main>
}
