"use client";
import {useEffect,useState} from "react";
const AYAH="فَإِنَّ مَعَ الْعُسْرِ يُسْرًا"; // Qur'an 94:5, display text only; do not alter.
export default function ElmiVerseMoment(){
 const [active,setActive]=useState(false),[burst,setBurst]=useState(false);
 useEffect(()=>{const start=window.setTimeout(()=>setActive(true),850);const flash=window.setTimeout(()=>setBurst(true),2500);const stop=window.setTimeout(()=>{setActive(false);setBurst(false)},8600);return()=>{clearTimeout(start);clearTimeout(flash);clearTimeout(stop)}},[]);
 const ignite=()=>{setActive(true);setBurst(false);window.setTimeout(()=>setBurst(true),80);window.setTimeout(()=>setBurst(false),1600)};
 return <div className={"elmiVerseMoment "+(active?"evmActive ":"")+(burst?"evmBurst":"")} aria-label="Animated Qur'an verse, Surah Ash-Sharh 94:5">
 <div className="evmLight" aria-hidden="true"><span className="evmBeam"/><span className="evmCore"/></div>
 <button type="button" className="evmVerse" onClick={ignite} aria-label="Illuminate verse 94:5"><span className="evmArabic" dir="rtl" lang="ar">{AYAH}</span><span className="evmReference">سورة الشرح · 94:5</span></button>
 <span className="evmHint">✦ Touch the verse to illuminate</span><div className="evmSparks" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i} style={{["--i" as string]:i,["--a" as string]:i*22.5+"deg"}}/>)}</div>
 <style jsx>{`.elmiVerseMoment{position:relative;isolation:isolate;overflow:hidden;min-height:235px;display:grid;place-content:center;text-align:center;margin:18px 0;border:1px solid #8ddbb83b;border-radius:24px;background:radial-gradient(ellipse at 50% 110%,#183d4266,transparent 60%),linear-gradient(115deg,#08151c,#10202c 60%,#101827);color:#f5f2e4}.evmVerse{position:relative;z-index:3;display:flex;flex-direction:column;align-items:center;gap:10px;cursor:pointer;border:0;background:transparent;color:inherit;padding:20px;opacity:0;transform:translateX(95vw) scale(.88);filter:blur(10px);transition:transform 2.4s cubic-bezier(.15,.8,.2,1),opacity 1s,filter 1.8s}.evmActive .evmVerse{opacity:1;transform:translateX(0) scale(1);filter:blur(0)}.evmArabic{font-family:"Amiri Quran","Amiri","Noto Naskh Arabic",serif;font-size:clamp(29px,5vw,58px);line-height:1.8;white-space:normal;text-shadow:0 0 10px #7be6d066}.evmReference{font-size:12px;letter-spacing:.12em;color:#a8d9c8}.evmLight{position:absolute;z-index:4;pointer-events:none;left:-20%;top:50%;width:45px;height:45px;transform:translate(-50%,-50%);opacity:0}.evmActive .evmLight{opacity:1;animation:evmTravel 2.4s .1s cubic-bezier(.2,.6,.2,1) both}.evmCore{position:absolute;inset:9px;border-radius:50%;background:#fff;box-shadow:0 0 10px 6px #fff9c2,0 0 32px 17px #7afee5,0 0 90px 35px #9f8cff88}.evmBeam{position:absolute;right:25px;top:50%;height:3px;width:130px;background:linear-gradient(90deg,transparent,#d6ffed);box-shadow:0 0 22px 6px #67ffe58c}.evmBurst .evmArabic{animation:evmPop .65s ease-out both;text-shadow:0 0 14px #fff,0 0 30px #8effd7,0 0 75px #9a8cff}.evmSparks{position:absolute;inset:0;pointer-events:none;z-index:2;display:grid;place-items:center}.evmSparks i{position:absolute;width:4px;height:4px;border-radius:50%;background:#e5ffec;opacity:0;box-shadow:0 0 9px 3px #a8ffe6}.evmBurst .evmSparks i{animation:evmSpark 1.1s ease-out both;animation-delay:calc(var(--i)*24ms)}.evmHint{position:absolute;bottom:12px;left:0;right:0;color:#a9c5bc;font-size:10px;letter-spacing:.08em;opacity:.8}@keyframes evmTravel{0%{left:-20%;top:67%;opacity:0}12%{opacity:1}70%{left:50%;top:49%}85%{left:52%;top:49%;opacity:1}100%{left:120%;top:25%;opacity:0}}@keyframes evmPop{0%{transform:scale(.94)}40%{transform:scale(1.12)}100%{transform:scale(1)}}@keyframes evmSpark{0%{opacity:1;transform:rotate(var(--a)) translateX(0) scale(1)}100%{opacity:0;transform:rotate(var(--a)) translateX(125px) scale(.2)}}@media(prefers-reduced-motion:reduce){.evmVerse{opacity:1;transform:none;filter:none;transition:none}.evmActive .evmLight,.evmBurst .evmArabic,.evmBurst .evmSparks i{animation:none}}`}</style></div>
}