"use client";
import {useEffect,useState} from "react";
type Verse={verse_key:string;arabic:string;english?:string};
export default function HudHudQuranText(){
 const [reference,setReference]=useState("1:1"),[verse,setVerse]=useState<Verse|null>(null),[status,setStatus]=useState(""),[font,setFont]=useState("uthmani"),[light,setLight]=useState(true);
 useEffect(()=>{let active=true;const match=/^(\\d{1,3}):(\\d{1,3})$/.exec(reference.trim());if(!match){setVerse(null);setStatus("Enter a reference such as 2:255");return}const ch=Number(match[1]),ay=Number(match[2]);if(ch<1||ch>114||ay<1){setVerse(null);setStatus("Invalid verse reference");return}
 setStatus("Loading verified Qur'an text…");setVerse(null);
 (async()=>{try{const local=await fetch("/quran-data/"+ch+".json");if(local.ok){const verses=await local.json() as Verse[];const found=verses.find(v=>v.verse_key===ch+":"+ay);if(found?.arabic){if(active){setVerse(found);setStatus("")}return}}
 const remote=await fetch("https://api.alquran.cloud/v1/ayah/"+ch+":"+ay+"/quran-uthmani");if(!remote.ok)throw Error("Unavailable");const data=await remote.json();if(!data?.data?.text)throw Error("Unavailable");if(active){setVerse({verse_key:ch+":"+ay,arabic:data.data.text});setStatus("")}
 }catch{if(active)setStatus("Verse unavailable. Please retry.")}})();return()=>{active=false}},[reference]);
 return <section className={"hhQuranText "+(light?"hhQuranLight":"")} aria-label="HudHud Quran verse display">
 <div className="hhQuranControls"><label>🦅 HudHud · Qur'an text <input aria-label="Verse reference" value={reference} onChange={e=>setReference(e.target.value)} placeholder="2:255" inputMode="text"/></label><label>Arabic font <select value={font} onChange={e=>setFont(e.target.value)}><option value="uthmani">Uthmani</option><option value="naskh">Naskh</option><option value="serif">Classic Arabic</option></select></label><label className="hhQuranToggle"><input type="checkbox" checked={light} onChange={e=>setLight(e.target.checked)}/> Elmi Light 💡</label></div>
 {verse?<div className="hhQuranVerse"><span>{verse.verse_key}</span><p dir="rtl" lang="ar" className={"hhArabic hhFont-"+font}>{verse.arabic}</p>{verse.english&&<p>{verse.english}</p>}<small>Arabic Qur'an text · unchanged. Font and glow affect presentation only.</small></div>:<p role="status">{status}</p>}
 <style jsx>{`.hhQuranText{padding:18px;border:1px solid #6cbd9777;border-radius:20px;background:#081b19;color:#eaf7ec;margin:20px 0}.hhQuranControls{display:flex;flex-wrap:wrap;align-items:end;gap:12px}.hhQuranControls label{display:flex;flex-direction:column;gap:6px;font-size:12px}.hhQuranControls input:not([type=checkbox]),.hhQuranControls select{border:1px solid #86bd9c77;border-radius:10px;background:#122a26;color:#fff;padding:10px}.hhQuranControls .hhQuranToggle{flex-direction:row;align-items:center;padding-bottom:10px}.hhQuranVerse{margin-top:16px;padding:16px;border-radius:18px;background:radial-gradient(circle at 50% 20%,#246b4b50,transparent 75%)}.hhQuranVerse>span{font-size:12px;color:#a8eac3}.hhArabic{font-size:clamp(29px,4.5vw,53px);line-height:2.2;text-align:center;white-space:normal;overflow-wrap:anywhere}.hhFont-uthmani{font-family:"Amiri Quran","Amiri","Noto Naskh Arabic",serif}.hhFont-naskh{font-family:"Noto Naskh Arabic","Traditional Arabic",serif}.hhFont-serif{font-family:"Scheherazade New","Amiri",serif}.hhQuranLight .hhArabic{color:#f6f5da;text-shadow:0 0 13px #9dfed17a,0 0 33px #59d8d95c;animation:hhVerseGlow 5s ease-in-out infinite}.hhQuranVerse small{color:#b2c8c0}@keyframes hhVerseGlow{50%{text-shadow:0 0 22px #c9ffc5b3,0 0 44px #b1a5ff99}}@media(prefers-reduced-motion:reduce){.hhQuranLight .hhArabic{animation:none}}`}</style>
 </section>
}