"use client";
import {useEffect,useRef,useState} from "react";
type Props={verse:string;onNavigate:(verse:string)=>void;onClose:()=>void};
const messages=[
 "Assalamu alaikum. I am HudHud, your Qur'an study companion. I can help you navigate, organize reflections, and explore reviewed connections.",
 "The Qur'an text is sacred. My guidance is a study aid, not a replacement for reliable tafsir or qualified scholars."
];
export default function HudHudVoice({verse,onNavigate,onClose}:Props){
 const [enabled,setEnabled]=useState(false),[status,setStatus]=useState("Voice is off"),[entry,setEntry]=useState(""),[history,setHistory]=useState<string[]>([]);
 const active=useRef(false);
 useEffect(()=>()=>{active.current=false;if(typeof window!=="undefined"&&"speechSynthesis" in window)window.speechSynthesis.cancel()},[]);
 const say=(message:string)=>{setHistory(h=>[...h.slice(-5),message]);if(!enabled)return;if(!("speechSynthesis" in window)){setStatus("Speech is unavailable in this browser.");return}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(message);utterance.lang="en-US";utterance.rate=.92;utterance.pitch=1.05;utterance.volume=.75;utterance.onstart=()=>setStatus("HudHud is speaking");utterance.onend=()=>setStatus("Ready");utterance.onerror=()=>setStatus("Speech could not play");window.speechSynthesis.speak(utterance)};
 const handle=(input:string)=>{const v=input.trim().toLowerCase();if(!v)return;setEntry("");if(v==="stop"||v==="quiet"){window.speechSynthesis?.cancel();setStatus("Voice paused");return}if(v==="hello"||v==="salam"){say(messages[0]);return}if(v==="help"){say("Try: where am I, explore, go to 2 colon 255, or stop.");return}if(v==="where am i"||v==="where am i?"||v==="current verse"){say("You are reading verse "+verse.replace(":"," colon ")+".");return}if(v==="explore"){say("You can open Rabbit Hole for reviewed verse connections, or Compare to study verses side by side.");return}const match=v.match(/(?:go to|open|verse)\s+(\d{1,3})\s*(?::|colon|verse)\s*(\d{1,3})/);if(match){const chapter=Number(match[1]),ayah=Number(match[2]);if(chapter>=1&&chapter<=114&&ayah>=1&&ayah<=286){onNavigate(chapter+":"+ayah);say("Opening verse "+chapter+" colon "+ayah+".");return}}say("I can help navigate verses and explain the tools. I do not generate unsourced religious interpretations.");};
 return <section className="hhvVoice" aria-label="HudHud voice companion"><div className="hhvVoiceHead"><div><strong>✦ HudHud Voice</strong><small>On-device browser speech · no microphone required</small></div><button type="button" onClick={()=>{window.speechSynthesis?.cancel();onClose()}} aria-label="Close voice panel">×</button></div><div className="hhvVoiceOrb" aria-hidden="true"><span>✧</span></div><p className="hhvVoiceStatus" role="status">{status}</p><div className="hhvVoiceControls"><button type="button" aria-pressed={enabled} onClick={()=>{setEnabled(x=>!x);window.speechSynthesis?.cancel();setStatus(enabled?"Voice is off":"Voice is on")}}>{enabled?"🔊 Voice ON":"🔇 Enable voice"}</button><button type="button" onClick={()=>say(messages[0])}>▶ Meet HudHud</button><button type="button" onClick={()=>{window.speechSynthesis?.cancel();setStatus("Stopped")}}>■ Stop</button></div><form onSubmit={e=>{e.preventDefault();handle(entry)}}><label htmlFor="hhvVoiceInput">Ask or give a navigation command</label><div><input id="hhvVoiceInput" value={entry} onChange={e=>setEntry(e.target.value)} maxLength={120} placeholder="e.g. where am I / go to 2:255"/><button type="submit">Ask →</button></div></form>{history.length>0&&<div className="hhvVoiceTranscript" aria-live="polite">{history.slice(-2).map((m,i)=><p key={i}>{m}</p>)}</div>}<p className="hhvVoicePrivacy">Voice playback uses your browser's speech engine, which may use device or platform services. No audio is recorded or uploaded by this feature. Commands are typed; microphone listening is not enabled.</p><style jsx>{`.hhvVoice{margin:10px 14px 16px;padding:18px;border:1px solid #6c63c9;border-radius:18px;background:radial-gradient(circle at 50% 30%,#412b8080,transparent 65%),#111c34;color:#f3efff}.hhvVoiceHead{display:flex;align-items:center;justify-content:space-between}.hhvVoiceHead div{display:grid;gap:4px}.hhvVoiceHead small,.hhvVoicePrivacy{font-size:11px;color:#c3c6dd}.hhvVoiceOrb{width:90px;height:90px;margin:18px auto 8px;display:grid;place-items:center;border-radius:50%;background:radial-gradient(circle,#36e9b0 0%,#4d53d3 38%,#231642 70%);box-shadow:0 0 25px #5b4ae999,0 0 55px #26d9a544;animation:hhvVoicePulse 3s ease-in-out infinite}.hhvVoiceOrb span{font-size:48px;color:#fff}.hhvVoiceStatus{text-align:center;font-size:12px}.hhvVoiceControls{display:flex;flex-wrap:wrap;gap:8px}.hhvVoice form{margin-top:14px}.hhvVoice form label{display:block;font-size:12px;margin-bottom:8px}.hhvVoice form>div{display:flex;gap:7px}.hhvVoice input{flex:1;min-width:0;background:#0b1428;color:white;border:1px solid #6674a4;border-radius:10px;padding:10px}.hhvVoiceTranscript{max-height:110px;overflow:auto;margin-top:10px}.hhvVoiceTranscript p{font-size:12px;line-height:1.6}.hhvVoicePrivacy{line-height:1.5;margin-top:14px}@keyframes hhvVoicePulse{50%{transform:scale(1.06);box-shadow:0 0 38px #7465ffaa,0 0 65px #26d9a566}}@media(prefers-reduced-motion:reduce){.hhvVoiceOrb{animation:none}}`}</style></section>
}