"use client";
import {useEffect,useMemo,useState} from "react";
import "./hudhud-vision.css";
import HudHudVoice from "./HudHudVoice";
type Journey={id:string;name:string;order:"canonical"|"revelation"|"custom";createdAt:number};
type Trail={origin:string;path:string[];createdAt:number};
type Concept={id:string;title:string;verses:string[];overview:string;createdAt:number};
const KEY="1muslim-hudhud-vision-v1";
const suggestions:Record<string,{verse:string;reason:string}[]>={
 "2:255":[{verse:"6:59",reason:"Both discuss Allah's encompassing knowledge."},{verse:"20:7",reason:"Both address Allah's knowledge of what is concealed."}],
 "6:59":[{verse:"31:34",reason:"Both address knowledge of the unseen."},{verse:"2:255",reason:"Both discuss the scope of Allah's knowledge."}],
 "31:34":[{verse:"6:59",reason:"Both address knowledge of the unseen."}],
 "20:7":[{verse:"2:255",reason:"Both address Allah's knowledge."}],
 "112:1":[{verse:"112:2",reason:"Adjacent verses in the same surah develop the declaration of tawhid."}]
};
const read=<T,>(key:string,fallback:T):T=>{try{const v=localStorage.getItem(key);return v?JSON.parse(v) as T:fallback}catch{return fallback}};
const reference=(s:string)=>/^([1-9]|[1-9][0-9]|1[01][0-4]):[1-9][0-9]{0,2}$/.test(s);
export default function HudHudVision({activeVerse,onNavigate,onModeChange}:{activeVerse:string;onNavigate:(verse:string)=>void;onModeChange?:(enabled:boolean)=>void}){
 const [voiceOpen,setVoiceOpen]=useState(false);
 const [on,setOn]=useState(false),[auto,setAuto]=useState(false),[delay,setDelay]=useState(3),[animated,setAnimated]=useState(true),[marked,setMarked]=useState<string[]>([]),[pinned,setPinned]=useState<string[]>([]),[compare,setCompare]=useState<string[]>([]),[concepts,setConcepts]=useState<Concept[]>([]),[trails,setTrails]=useState<Trail[]>([]),[path,setPath]=useState<string[]>([]),[warning,setWarning]=useState(false),[warned,setWarned]=useState(false),[notes,setNotes]=useState<Record<string,string>>({}),[marker,setMarker]=useState<"purple"|"blue"|"green">("green"),[journeys,setJourneys]=useState<Journey[]>([]),[order,setOrder]=useState<Journey["order"]>("canonical"),[title,setTitle]=useState(""),[candidate,setCandidate]=useState(""),[ready,setReady]=useState(false),[tab,setTab]=useState<"insights"|"compare"|"journeys"|"notes">("insights");
 useEffect(()=>{const s=read<Record<string,unknown>>(KEY,{});setOn(localStorage.getItem("1muslim-hudhud-vision-enabled") !== "off" && Boolean(s.on));setAuto(Boolean(s.auto));setDelay(Number(s.delay)||3);setAnimated(s.animated!==false);setMarked(Array.isArray(s.marked)?s.marked as string[]:[]);setPinned(Array.isArray(s.pinned)?s.pinned as string[]:[]);setCompare(Array.isArray(s.compare)?s.compare as string[]:[]);setConcepts(Array.isArray(s.concepts)?s.concepts as Concept[]:[]);setTrails(Array.isArray(s.trails)?s.trails as Trail[]:[]);setNotes(s.notes&&typeof s.notes==="object"?s.notes as Record<string,string>:{});setJourneys(Array.isArray(s.journeys)?s.journeys as Journey[]:[]);setReady(true)},[]);
 useEffect(()=>{if(ready)onModeChange?.(on)},[on,ready,onModeChange]);
 useEffect(()=>{const allowed=()=>localStorage.getItem("1muslim-hudhud-vision-enabled") !== "off";const toggle=()=>setOn(v=>allowed()?!v:false);const settingsUpdate=()=>{if(!allowed())setOn(false)};window.addEventListener("1muslim:hudhud-vision-settings-updated",settingsUpdate);window.addEventListener("1muslim:hudhud-vision-toggle",toggle);return()=>{window.removeEventListener("1muslim:hudhud-vision-toggle",toggle);window.removeEventListener("1muslim:hudhud-vision-settings-updated",settingsUpdate)}},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(KEY,JSON.stringify({on,auto,delay,animated,marked,pinned,compare,concepts,trails,notes,journeys}))}catch{}},[ready,on,auto,delay,animated,marked,pinned,compare,concepts,trails,notes,journeys]);
 useEffect(()=>{if(!on||!auto||!reference(activeVerse)||marked.includes(activeVerse))return;const timer=window.setTimeout(()=>setMarked(v=>v.includes(activeVerse)?v:[...v,activeVerse]),delay*1000);return()=>clearTimeout(timer)},[on,auto,delay,activeVerse,marked]);
 const togglePin=()=>setPinned(v=>v.includes(activeVerse)?v.filter(x=>x!==activeVerse):[...v,activeVerse]);
 const addCompare=(v:string)=>setCompare(c=>c.includes(v)?c:c.length<4?[...c,v]:c);
 const follow=(verse:string)=>{if(!reference(verse))return;const next=path.length?[...path,verse]:[activeVerse,verse];setPath(next);onNavigate(verse);if(next.length>4&&!warned){setWarning(true);setWarned(true)}};
 const back=()=>{if(path.length<2)return;const next=path.slice(0,-1);setPath(next.length>1?next:[]);onNavigate(next[next.length-1])};
 const returnToStart=()=>{if(!path.length)return;setTrails(t=>[{origin:path[0],path,createdAt:Date.now()},...t].slice(0,40));onNavigate(path[0]);setPath([]);setWarning(false);setWarned(false)};
 const overview=useMemo(()=>compare.length<2?"Select two to four verses to compare.":`Study comparison: ${compare.join(" → ")}. Review the wording, context, and reliable tafsir for each verse before drawing conclusions. Verse order reflects your selected sequence; no AI-generated religious ruling is implied.`,[compare]);
 const saveConcept=()=>{if(compare.length<2)return;setConcepts(c=>[{id:String(Date.now()),title:title.trim()||"Study of "+compare.join(", "),verses:[...compare],overview,createdAt:Date.now()},...c]);setTitle("")};
 const createJourney=()=>setJourneys(j=>[{id:String(Date.now()),name:title.trim()||"My Qur'an Completion",order,createdAt:Date.now()},...j]);
 const markPrevious=()=>{const [chapter,verse]=activeVerse.split(":").map(Number);if(!chapter||!verse)return;const entries=Array.from({length:Math.max(0,verse-1)},(_,i)=>chapter+":"+(i+1));setMarked(m=>Array.from(new Set([...m,...entries])))};
 return <div className={"hhv "+(on?"hhvOn":"")} data-hudhud-mode={on?"on":"off"}>
 <div className="hhvTop"><div><span className="hhvEyebrow">HUDHUD VISION · QUR'AN STUDIO</span><strong>🦜 Contextual reading companion</strong></div></div>
 {on&&<><div className="hhvVoiceLaunch"><button type="button" aria-expanded={voiceOpen} onClick={()=>setVoiceOpen(v=>!v)}>{voiceOpen?"✕ Close HudHud Voice":"✦ Talk with HudHud"}</button><small>Opt-in voice guidance · no microphone</small></div>{voiceOpen&&<HudHudVoice verse={activeVerse} onNavigate={onNavigate} onClose={()=>setVoiceOpen(false)}/>}<div className="hhvLens"><span>◉ FOCUS LENS</span><strong>{activeVerse}</strong><small>{marked.includes(activeVerse)?"✓ Marked read":"The centered verse drives HudHud's context"}</small></div>
 <div className="hhvActions"><button onClick={togglePin}>{pinned.includes(activeVerse)?"📍 Pinned":"📍 Pin verse"}</button><button onClick={()=>{addCompare(activeVerse);setTab("compare")}}>⚖ Compare ({compare.length}/4)</button><button onClick={()=>setTab("notes")}>✎ Notes</button><button onClick={()=>setMarked(m=>m.includes(activeVerse)?m.filter(x=>x!==activeVerse):[...m,activeVerse])}>{marked.includes(activeVerse)?"✓ Read":"Mark read"}</button></div>
 <div className="hhvTabs">{(["insights","compare","journeys","notes"] as const).map(t=><button key={t} className={tab===t?"selected":""} onClick={()=>setTab(t)}>{t==="insights"?"🕳 Rabbit Hole":t==="compare"?"⚖ Compare":t==="journeys"?"📖 Journeys":"✎ Notes"}</button>)}</div>
 {tab==="insights"&&<section className="hhvPanel"><h3>Connected passages</h3><p className="hhvCaution">Curated thematic suggestions, not claims of scholarly consensus. Consult sourced tafsir for established explanations.</p>{(suggestions[activeVerse]||[]).map(x=><button className="hhvConnection" key={x.verse} onClick={()=>follow(x.verse)}><strong>{x.verse} →</strong><small>{x.reason}</small></button>)}{!suggestions[activeVerse]?.length&&<p>No reviewed connections are listed for this verse yet. HudHud will not invent one.</p>}{path.length>0&&<div className="hhvTrail"><strong>🕳 Journey · {path.length-1} connections deep</strong><p>{path.join(" → ")}</p><button onClick={back}>← Previous</button><button onClick={returnToStart}>↩ Return to original {path[0]}</button></div>}{trails.length>0&&<details><summary>Saved exploration history ({trails.length})</summary>{trails.map(t=><p key={t.createdAt}>{t.path.join(" → ")} <button onClick={()=>onNavigate(t.origin)}>Return to {t.origin}</button></p>)}</details>}</section>}
 {tab==="compare"&&<section className="hhvPanel"><h3>Compare up to four verses</h3><div className="hhvCompare">{compare.map((v,i)=><div key={v}><b>{i+1}. {v}</b><span><button disabled={i===0} onClick={()=>setCompare(c=>{const n=[...c];[n[i-1],n[i]]=[n[i],n[i-1]];return n})}>↑</button><button disabled={i===compare.length-1} onClick={()=>setCompare(c=>{const n=[...c];[n[i+1],n[i]]=[n[i],n[i+1]];return n})}>↓</button><button onClick={()=>setCompare(c=>c.filter(x=>x!==v))}>×</button></span></div>)}</div><div className="hhvActions"><input aria-label="Verse reference" placeholder="e.g. 6:59" value={candidate} onChange={e=>setCandidate(e.target.value)}/><button disabled={!reference(candidate)||compare.length>=4} onClick={()=>{addCompare(candidate);setCandidate("")}}>+ Add</button></div><p className="hhvCaution">{overview}</p><input aria-label="Concept title" placeholder="Concept title" value={title} onChange={e=>setTitle(e.target.value)}/><button disabled={compare.length<2} onClick={saveConcept}>💾 Save concept</button><details><summary>Saved concepts ({concepts.length})</summary>{concepts.map(c=><div className="hhvSaved" key={c.id}><strong>{c.title}</strong><small>{c.verses.join(" → ")}</small><button onClick={()=>setCompare(c.verses.slice(0,4))}>Compare again</button></div>)}</details></section>}
 {tab==="journeys"&&<section className="hhvPanel"><h3>Qur'an completion journeys</h3><select aria-label="Reading order" value={order} onChange={e=>setOrder(e.target.value as Journey["order"])}><option value="canonical">Front to back</option><option value="revelation">Revelation order (chronology varies)</option><option value="custom">Custom order</option></select><input aria-label="Journey name" placeholder="Journey name (optional)" value={title} onChange={e=>setTitle(e.target.value)}/><button onClick={createJourney}>+ Create journey</button><p className="hhvCaution">Journey planning is stored on this device. Custom sequencing, complete chronology, progress sharing and syncing are not connected yet.</p><div className="hhvActions"><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Auto-mark focused verse</label><select aria-label="Focus duration" value={delay} onChange={e=>setDelay(Number(e.target.value))}><option value={2}>2 sec</option><option value={3}>3 sec</option><option value={5}>5 sec</option></select><label><input type="checkbox" checked={animated} onChange={e=>setAnimated(e.target.checked)}/> Lens glow</label></div><p>{marked.length} verses marked read on this device</p><button onClick={markPrevious}>✓ Mark previous verses in this surah</button>{journeys.map(j=><div className="hhvSaved" key={j.id}><strong>{j.name}</strong><small>{j.order} · Created {new Date(j.createdAt).toLocaleDateString()}</small></div>)}</section>}
 {tab==="notes"&&<section className="hhvPanel"><h3>Notes on {activeVerse}</h3><div className="hhvMarkers">{(["purple","blue","green"] as const).map(c=><button key={c} className={marker===c?"selected":""} onClick={()=>setMarker(c)} aria-label={c+" marker"} style={{background:c==="purple"?"#9563d8":c==="blue"?"#448ad7":"#40db95"}}/>)}</div><textarea aria-label="Verse reflection" placeholder="Write your reflection…" value={notes[activeVerse]||""} onChange={e=>setNotes(n=>({...n,[activeVerse]:e.target.value}))}/><small>Notes save locally. Marker selection changes your writing accent.</small></section>}
 {warning&&<div className="hhvWarning" role="dialog" aria-label="Reading focus reminder"><h3>🦜 You're more than three connections deep</h3><p>You started at <strong>{path[0]}</strong>. Would you like to return to your original reading position? Your exploration path is preserved.</p><div className="hhvActions"><button onClick={returnToStart}>↩ Return to reading</button><button onClick={()=>setWarning(false)}>Continue exploring</button></div><small>One reminder per exploration, never a suspicious-behavior flag.</small></div>}
 </>}
 </div>
}
