"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {createClient} from "../../../utils/supabase/client";
type Take={id:string;blob:Blob;url:string};
const BUCKET="quran-recitation-vault";
export default function VerseRecorder({verse}:{verse:string}){
 const [open,setOpen]=useState(false),[recording,setRecording]=useState(false),[takes,setTakes]=useState<Take[]>([]),[saved,setSaved]=useState<{path:string;url:string}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[echo,setEcho]=useState(false);
 const media=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),urls=useRef<string[]>([]);
 const cleanup=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;media.current=null;};
 const clearTakes=useCallback(()=>{setTakes(old=>{old.forEach(t=>URL.revokeObjectURL(t.url));return []})},[]);
 useEffect(()=>{const openRecorder=()=>{const node=document.querySelector<HTMLElement>(`[data-recorder-verse="${verse}"]`);if(node?.closest(".omAyahFocused"))setOpen(true)};window.addEventListener("1muslim:quran-record",openRecorder);return()=>window.removeEventListener("1muslim:quran-record",openRecorder)},[]);
 useEffect(()=>{let active=true;setSaved(null);setMessage("");clearTakes();const db=createClient();void (async()=>{const {data:{user}}=await db.auth.getUser();if(!user)return;const {data}=await db.from("quran_recitations").select("storage_path").eq("user_id",user.id).eq("verse_key",verse).maybeSingle();if(!active||!data?.storage_path)return;const signed=await db.storage.from(BUCKET).createSignedUrl(data.storage_path,3600);if(active&&signed.data?.signedUrl)setSaved({path:data.storage_path,url:signed.data.signedUrl})})();return()=>{active=false}},[verse,clearTakes]);
 useEffect(()=>()=>{cleanup();urls.current.forEach(u=>URL.revokeObjectURL(u))},[]);
 const start=async()=>{setMessage("");if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){setMessage("Audio recording is not supported in this browser.");return}try{const s=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=s;const preferred=["audio/webm;codecs=opus","audio/mp4","audio/webm"].find(t=>MediaRecorder.isTypeSupported(t));const recorder=new MediaRecorder(s,preferred?{mimeType:preferred}:undefined);chunks.current=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunks.current,{type:recorder.mimeType||"audio/webm"});if(blob.size){const url=URL.createObjectURL(blob);urls.current.push(url);setTakes(old=>[...old,{id:crypto.randomUUID(),blob,url}])}cleanup();setRecording(false)};recorder.start();media.current=recorder;setRecording(true)}catch{cleanup();setMessage("Microphone permission was denied or unavailable.")}};
 const stop=()=>{if(media.current?.state==="recording")media.current.stop()};
 const discard=(id:string)=>setTakes(old=>{const take=old.find(t=>t.id===id);if(take)URL.revokeObjectURL(take.url);return old.filter(t=>t.id!==id)});
 const save=async(take:Take)=>{setBusy(true);setMessage("");const db=createClient();try{const {data:{user}}=await db.auth.getUser();if(!user)throw Error("Sign in to save recitations privately.");const ext=take.blob.type.includes("mp4")?"m4a":take.blob.type.includes("ogg")?"ogg":"webm";const path=`${user.id}/${verse.replace(":","-")}/${crypto.randomUUID()}.${ext}`;const uploaded=await db.storage.from(BUCKET).upload(path,take.blob,{contentType:take.blob.type||"audio/webm",upsert:false});if(uploaded.error)throw uploaded.error;const row=await db.from("quran_recitations").upsert({user_id:user.id,verse_key:verse,storage_path:path,mime_type:take.blob.type||"audio/webm",updated_at:new Date().toISOString()},{onConflict:"user_id,verse_key"}).select("storage_path").single();if(row.error){await db.storage.from(BUCKET).remove([path]);throw row.error}const previous=saved?.path;if(previous&&previous!==path)await db.storage.from(BUCKET).remove([previous]);const signed=await db.storage.from(BUCKET).createSignedUrl(path,3600);setSaved({path,url:signed.data?.signedUrl||""});clearTakes();setMessage("Saved privately to your Secure Vault ✓");window.dispatchEvent(new CustomEvent("1muslim:quran-recitation-saved",{detail:{verse}}))}catch(e){setMessage(e instanceof Error?e.message:"Could not save this recording.")}finally{setBusy(false)}};
 const share=async()=>{if(!saved)return;const db=createClient();const {data}=await db.storage.from(BUCKET).download(saved.path);if(!data){setMessage("Could not prepare the recording.");return}const file=new File([data],`Quran-${verse}.webm`,{type:data.type||"audio/webm"});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:`My recitation of Qur'an ${verse}`})}catch{}}else{const url=URL.createObjectURL(data);const a=document.createElement("a");a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setMessage("Downloaded privately. Share the file only if you choose.")}};
 return <div className="qrv" data-recorder-verse={verse}>
 <button type="button" className="qrv-open" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><img src="/assets/hudhud-logo.PNG" alt=""/> <span>{saved?"✓ My saved recitation":"🎙 Record this ayah"}</span><small>{verse}</small></button>
 {open&&<div className="qrv-panel"><div className="qrv-top"><strong>🎙 Qur'an Recording Studio · {verse}</strong><button onClick={()=>setOpen(false)} aria-label="Close recording studio">×</button></div><p>Practice freely. Only the take you choose to keep is stored in your private Secure Vault.</p>
 {saved&&<div className="qrv-saved"><b>🔒 Your saved recitation · {verse}</b><audio controls src={saved.url}/><button onClick={()=>void share()}>Share a copy ↗</button><small>Private by default. Saving another take replaces this one.</small></div>}
 <div className="qrv-controls"><button type="button" className={recording?"qrv-stop":"qrv-record"} disabled={busy} onClick={()=>recording?stop():void start()}>{recording?"■ Stop recording":"● Record a take"}</button><label><input type="checkbox" checked={echo} onChange={e=>setEcho(e.target.checked)}/> Soft playback echo</label></div>
 <div className="qrv-takes">{takes.map((take,i)=><div className="qrv-take" key={take.id}><strong>Take {i+1}</strong><audio controls src={take.url} style={echo?{filter:"none"}:{}}/><div><button disabled={busy||recording} onClick={()=>void save(take)}>✓ Keep this take</button><button disabled={busy} onClick={()=>discard(take.id)}>✕ Discard</button></div></div>)}</div>
 {echo&&<small>Audio enhancement is planned; original audio plays unchanged for now.</small>}
 {message&&<p role="status" className="qrv-message">{message}</p>}
 </div>}
 <style jsx>{`
 .qrv{margin:14px 0;color:#f2fff9}.qrv button{cursor:pointer}.qrv-open{display:flex;align-items:center;gap:10px;padding:11px 15px;width:100%;border:1px solid #56d6a37d;border-radius:16px;background:linear-gradient(120deg,#103b35,#181f38);color:#fff;text-align:left}.qrv-open img{width:35px;height:35px;object-fit:contain}.qrv-open span{flex:1;font-weight:800}.qrv-open small{color:#a8ead0}.qrv-panel{margin-top:9px;padding:17px;border:1px solid #73e5bb77;border-radius:19px;background:linear-gradient(140deg,#102e30,#15172c);box-shadow:0 12px 40px #0008;animation:qrvDrop .3s ease}.qrv-top{display:flex;align-items:center;justify-content:space-between;gap:12px}.qrv-top button{font-size:25px;color:#fff;background:transparent;border:0}.qrv-panel p,.qrv-panel small{color:#c4dcd5}.qrv-controls{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin:16px 0}.qrv-controls label{font-size:12px}.qrv-record,.qrv-stop{border:0;border-radius:999px;padding:12px 18px;font-weight:800;color:white;background:#16866d}.qrv-stop{background:#b82343;animation:qrvPulse 1.2s infinite}.qrv-saved,.qrv-take{display:grid;gap:9px;border:1px solid #8ad9bf44;border-radius:14px;padding:13px;margin:10px 0;background:#ffffff0b;animation:qrvDrop .3s ease}.qrv-saved audio,.qrv-take audio{width:100%}.qrv-saved button,.qrv-take button{border:1px solid #80d4b277;border-radius:10px;background:#164c43;color:white;padding:9px 12px;margin-right:8px}.qrv-message{color:#a7ffcb!important}@keyframes qrvDrop{from{opacity:0;transform:translateY(-14px) scale(.97)}to{opacity:1;transform:none}}@keyframes qrvPulse{50%{box-shadow:0 0 18px #f4476e}}@media(prefers-reduced-motion:reduce){.qrv-panel,.qrv-take,.qrv-stop{animation:none}}
 `}</style></div>
}
