"use client";
import {useEffect,useState} from "react";
import {createClient} from "../../../utils/supabase/client";
type Tip={id:string;verse_key:string;title:string;description:string|null;media_type:"image"|"video"|"youtube";media_url:string;credit:string|null};
const safeUrl=(raw:string)=>{try{const u=new URL(raw);return u.protocol==="https:"?u:null}catch{return null}};
const youtubeId=(raw:string)=>{const u=safeUrl(raw);if(!u)return null;const host=u.hostname.toLowerCase();if(host==="youtu.be")return /^[\w-]{11}$/.test(u.pathname.slice(1))?u.pathname.slice(1):null;if(host==="youtube.com"||host==="www.youtube.com"||host==="m.youtube.com"){const id=u.pathname.startsWith("/shorts/")?u.pathname.split("/")[2]:u.searchParams.get("v");return id&&/^[\w-]{11}$/.test(id)?id:null}return null};
export default function VerseMediaTips({verse}:{verse:string}){
 const [tips,setTips]=useState<Tip[]>([]),[open,setOpen]=useState<string|null>(null);
 useEffect(()=>{let live=true;createClient().from("verse_media_tips").select("id,verse_key,title,description,media_type,media_url,credit").eq("verse_key",verse).eq("published",true).order("sort_order",{ascending:true}).limit(8).then(({data,error})=>{if(live)setTips(error?[]:(data||[]) as Tip[])});return()=>{live=false}},[verse]);
 if(!tips.length)return null;
 return <aside className="omVerseTips" aria-label={"Learning media for verse "+verse}><div className="omVerseTipsTitle"><span>✦ VISUAL LEARNING</span><strong>Explore {verse}</strong><small>Optional lesson resources</small></div><div className="omVerseTipsList">{tips.map(t=>{const url=safeUrl(t.media_url),id=t.media_type==="youtube"?youtubeId(t.media_url):null;return <article key={t.id} className="omVerseTip"><button className="omVerseTipButton" onClick={()=>setOpen(x=>x===t.id?null:t.id)} aria-expanded={open===t.id}><span className="omVerseTipIcon">{t.media_type==="image"?"🖼️":"▶"}</span><span><strong>{t.title}</strong><small>{t.media_type==="image"?"Image guide":"Watch lesson"} · Tap to {open===t.id?"close":"open"}</small></span><b>⌄</b></button>{open===t.id&&<div className="omVerseTipContent">{t.media_type==="image"&&url?<img src={url.href} alt={t.description||t.title} loading="lazy"/>:t.media_type==="youtube"&&id?<iframe title={t.title} src={"https://www.youtube-nocookie.com/embed/"+id} loading="lazy" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:t.media_type==="video"&&url?<video src={url.href} controls preload="none" playsInline/>:<p>Media link unavailable.</p>}{t.description&&<p>{t.description}</p>}{t.credit&&<small>Source: {t.credit}</small>}</div>}</article>})}</div><style jsx>{`.omVerseTips{min-width:0;border:1px solid #bca76a55;border-radius:17px;background:var(--panel2);padding:13px;align-self:start}.omVerseTipsTitle{display:flex;flex-direction:column;gap:4px;padding:3px 3px 12px}.omVerseTipsTitle>span{font-size:9px;font-weight:900;letter-spacing:.12em;color:#c4a35b}.omVerseTipsTitle strong{font-size:16px}.omVerseTipsTitle small{font-size:11px;color:var(--muted)}.omVerseTipsList{display:grid;gap:9px}.omVerseTip{background:var(--panel);border:1px solid var(--line);border-radius:12px;overflow:hidden}.omVerseTipButton{width:100%;display:flex;gap:10px;align-items:center;border:0;background:transparent;color:var(--text);padding:11px;cursor:pointer;text-align:left}.omVerseTipButton>span:nth-child(2){display:grid;gap:4px;flex:1;min-width:0}.omVerseTipButton strong{font-size:12px}.omVerseTipButton small{font-size:10px;color:var(--muted)}.omVerseTipIcon{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:#bca76a22;flex-shrink:0}.omVerseTipContent{padding:0 10px 11px;animation:omTipReveal .24s ease-out}.omVerseTipContent img,.omVerseTipContent video,.omVerseTipContent iframe{display:block;width:100%;max-height:300px;aspect-ratio:16/9;object-fit:contain;border:0;border-radius:9px;background:#0e1917}.omVerseTipContent p{font-size:12px;line-height:1.6}.omVerseTipContent small{font-size:10px;color:var(--muted)}@keyframes omTipReveal{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}@media(prefers-reduced-motion:reduce){.omVerseTipContent{animation:none}}`}</style></aside>
}
