"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import SiteNav from "../../components/SiteNav";
import {createClient} from "../../../utils/supabase/client";
type Question={id:string;topic:string;level:number;prompt:string;options:string[];correct_index:number;explanation:string;source_label:string;source_url:string};
const starter:Question[]=[
{id:"starter-112",topic:"Tawhid",level:1,prompt:"Which surah begins by affirming that Allah is One?",options:["Al-Ikhlas","Al-Falaq","An-Nas","Al-Asr"],correct_index:0,explanation:"Al-Ikhlas opens with the declaration of Allah's oneness.",source_label:"Qur’an 112:1",source_url:"/elm-tent/quran?surah=112&ayah=1"},
{id:"starter-1",topic:"Prayer",level:1,prompt:"Which surah is recited in every rak’ah of salah?",options:["Al-Fil","Al-Fatihah","Al-Kawthar","Al-Masad"],correct_index:1,explanation:"Al-Fatihah is the opening chapter recited in salah.",source_label:"Qur’an 1:1–7",source_url:"/elm-tent/quran?surah=1&ayah=1"}
];
export default function ElmLessons(){
 const [questions,setQuestions]=useState<Question[]>(starter),[dbReady,setDbReady]=useState(false),[userId,setUserId]=useState<string|null>(null);
 const [level,setLevel]=useState(1),[streak,setStreak]=useState(0),[round,setRound]=useState(0),[choice,setChoice]=useState<number|null>(null),[answer,setAnswer]=useState<number|null>(null),[note,setNote]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{const s=createClient();void s.auth.getUser().then(({data})=>setUserId(data.user?.id||null));void s.from("elm_curriculum_questions").select("id,topic,level,prompt,options,correct_index,explanation,source_label,source_url").order("level").limit(300).then(({data,error})=>{if(!error&&data?.length){setQuestions(data as Question[]);setDbReady(true)}})},[]);
 const pool=useMemo(()=>questions.filter(q=>q.level<=level+1),[questions,level]);
 const question=pool[round%Math.max(1,pool.length)];
 const shuffled=useMemo(()=>{if(!question)return [];const opts=question.options.map((label,index)=>({label,index}));let seed=round+question.id.length;for(let i=opts.length-1;i>0;i--){seed=(seed*1664525+1013904223)>>>0;const j=seed%(i+1);[opts[i],opts[j]]=[opts[j],opts[i]]}return opts},[question,round]);
 if(!question)return <main><SiteNav/><p>No curriculum questions available.</p></main>;
 const submit=async()=>{if(choice===null||answer!==null)return;const correct=choice===question.correct_index;setAnswer(choice);setStreak(s=>correct?s+1:0);setLevel(v=>correct&&streak>=1?Math.min(10,v+1):!correct?Math.max(1,v-1):v);if(userId&&dbReady){const s=createClient();const {data:prior}=await s.from("elm_curriculum_progress").select("attempts,correct_count").eq("user_id",userId).eq("question_id",question.id).maybeSingle();await s.from("elm_curriculum_progress").upsert({user_id:userId,question_id:question.id,attempts:(prior?.attempts||0)+1,correct_count:(prior?.correct_count||0)+(correct?1:0),last_answered_at:new Date().toISOString()})}};
 const saveNote=async()=>{if(!userId){setMessage("Sign in to save a lesson note.");return}const body=note.trim()||question.explanation;const {error}=await createClient().from("elm_learning_notes").insert({user_id:userId,question_id:dbReady?question.id:null,body,source_url:question.source_url});setMessage(error?"Could not save note. Apply the curriculum migration first.":"Saved! Open your Elm Tent notes anytime.")};
 return <main style={{minHeight:"100vh",background:"var(--bg)",color:"var(--text)"}}><SiteNav/><section style={{maxWidth:740,margin:"auto",padding:"40px 20px 120px"}}><Link href="/elm-tent">← Elm Tent</Link><h1>📚 Elm Tent · Living Lessons</h1><p>Learn continuously. Questions get harder after consecutive correct answers and ease up when you need more practice.</p><p><b>Level {level}/10</b> · Correct streak: {streak} · Question {round+1}</p>{!dbReady&&<p role="status">Starter lessons are available. Connect the curriculum database to unlock the full question bank and saved progress.</p>}<article style={{padding:24,border:"1px solid var(--line)",borderRadius:20,background:"var(--panel)"}}><small>{question.topic} · Difficulty {question.level}</small><h2>{question.prompt}</h2><div style={{display:"grid",gap:10}}>{shuffled.map(x=><button key={x.index} disabled={answer!==null} onClick={()=>setChoice(x.index)} style={{padding:14,borderRadius:12,border:"1px solid var(--line)",textAlign:"left",background:choice===x.index?"#246246":"var(--panel2)",color:"var(--text)"}}>{x.label}</button>)}</div>{answer===null?<button onClick={()=>void submit()} disabled={choice===null} style={{marginTop:16,padding:12}}>Check answer</button>:<div style={{marginTop:18}}><h3>{answer===question.correct_index?"✓ Correct!":"Let's learn from this."}</h3><p>{question.explanation}</p><Link href={question.source_url}>📖 Study the source in Qur’an Studio · {question.source_label} →</Link><p>📝 Save this explanation as a note to bring back to Elm Tent lessons.</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="What did you learn? (optional)" style={{display:"block",width:"100%",minHeight:80,margin:"12px 0",padding:12}}/><button onClick={()=>void saveNote()}>Save as Note</button>{" "}<button onClick={()=>{setRound(v=>v+1);setChoice(null);setAnswer(null);setNote("");setMessage("")}}>Next question →</button></div>}</article>{message&&<p role="status">{message}</p>}</section></main>
}