"use client";

import Link from "next/link";
import { useState } from "react";
import SiteNav from "../components/SiteNav";
import { createClient } from "../../utils/supabase/client";

export default function SupportPage(){
 const [type,setType]=useState("Support request"),[message,setMessage]=useState(""),[sent,setSent]=useState(false),[error,setError]=useState("");
 const submit=async()=>{setError("");setSent(false);const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setError("Sign in is required to submit a support request.");return}if(!message.trim()){setError("Tell us what you need help with.");return}
 const {error}=await s.from("support_requests").insert({user_id:user.id,type,message:message.trim(),status:"open"});if(error){setError(error.message);return}setMessage("");setSent(true)};
 return <main className="support"><style jsx>{`
 .support{min-height:100vh;background:var(--bg);color:var(--text)}.shell{max-width:1000px;margin:auto;padding:34px 18px 80px}.hero{padding:28px;border:1px solid #243229;border-radius:24px;background:radial-gradient(circle at 85% 10%,rgba(132,174,116,.14),transparent 35%),#09100b}.eyebrow{font-size:10px;letter-spacing:.16em;color:#8ca48d;font-weight:900}.hero h1{font-size:clamp(38px,6vw,58px);letter-spacing:-.07em;margin:8px 0}.hero p{color:#89978e;line-height:1.7;font-size:13px;max-width:680px}.grid{display:grid;grid-template-columns:1fr 1.2fr;gap:14px;margin-top:18px}.card{border:1px solid #243229;border-radius:19px;background:#09100b;padding:20px}.card h2{font-size:18px;margin:0 0 8px}.card p,.card li{font-size:11px;color:#819087;line-height:1.65}.card ul{padding-left:18px}.select,.textarea{width:100%;box-sizing:border-box;background:#070d08;color:#e9f0ea;border:1px solid #29372e;border-radius:11px;padding:11px;font:inherit;font-size:12px;margin-top:7px}.textarea{min-height:150px;resize:vertical}.label{display:block;font-size:10px;color:#89978e;margin:14px 0}.button{margin-top:12px;border:0;border-radius:999px;background:#d8e9bd;color:#071008;padding:12px 17px;font-weight:850;cursor:pointer}.error{margin-top:12px;color:#ffcaca;font-size:10px}.success{margin-top:12px;color:#cce7c2;font-size:10px}.back{display:inline-block;margin-top:14px;color:#d8e9bd;font-size:11px;text-decoration:none}@media(max-width:760px){.grid{grid-template-columns:1fr}.shell{padding:22px 13px 60px}}
 `}</style><SiteNav/><div className="shell"><section className="hero"><span className="eyebrow">1MUSLIM SUPPORT</span><h1>We’re here to help.</h1><p>Request an account change, report a Live issue, ask about a feature, or tell us what went wrong. HudHud can help triage common questions while the 1Muslim team handles account and moderation decisions.</p><Link href="/streaming" className="back">← Back to 1Muslim</Link></section>
 <div className="grid"><section className="card"><h2>What can I request?</h2><ul><li>Account and sign-in help</li><li>Live stream or comment reports</li><li>Profile or saved-content changes</li><li>Feature requests</li><li>Technical problems</li><li>Safety or community concerns</li></ul><p><strong>Account required:</strong> support requests are tied to your authenticated account so we can follow up securely.</p></section>
 <section className="card"><h2>Submit a request</h2><label className="label">Request type<select className="select" value={type} onChange={e=>setType(e.target.value)}><option>Support request</option><option>Account change</option><option>Report a Live</option><option>Report a comment</option><option>Feature request</option><option>Technical issue</option></select></label><label className="label">What happened?<textarea className="textarea" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Describe what you need help with…"/></label><button className="button" onClick={submit}>Send request →</button>{error&&<div className="error">{error}</div>}{sent&&<div className="success">Request submitted. We’ll keep it attached to your account.</div>}</section></div></div></main>;
}
