"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import SiteNav from "../components/SiteNav";
import {createClient} from "../../utils/supabase/client";

type Article={id:string;title:string;slug:string;category:string;excerpt:string;content:string;cover_emoji:string;published:boolean;created_at:string};
type Topic={id:string;name:string;slug:string};

export default function NewsletterPage(){
 const s=createClient(); const [articles,setArticles]=useState<Article[]>([]); const [topics,setTopics]=useState<Topic[]>([]); const [subs,setSubs]=useState<string[]>([]); const [admin,setAdmin]=useState(false);
 const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState("");
 const [form,setForm]=useState({title:"",slug:"",category:"Qur’an",excerpt:"",content:"",cover_emoji:"✦"});
 const load=async()=>{const {data:{user}}=await s.auth.getUser(); const [{data:a},{data:t}]=await Promise.all([s.from("newsletter_articles").select("*").eq("published",true).order("created_at",{ascending:false}),s.from("newsletter_topics").select("*").order("name")]);setArticles((a??[]) as Article[]);setTopics((t??[]) as Topic[]);if(user){const {data:ad}=await s.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();setAdmin(!!ad);const {data:sub}=await s.from("newsletter_subscriptions").select("topic_id").eq("user_id",user.id);setSubs((sub??[]).map(x=>x.topic_id));}};
 useEffect(()=>{void load()},[]);
 const toggle=async(id:string)=>{const {data:{user}}=await s.auth.getUser();if(!user){setMsg("Sign in to subscribe to topics.");return;}if(subs.includes(id)){await s.from("newsletter_subscriptions").delete().eq("user_id",user.id).eq("topic_id",id);setSubs(x=>x.filter(y=>y!==id))}else{await s.from("newsletter_subscriptions").insert({user_id:user.id,topic_id:id});setSubs(x=>[...x,id])}};
 const publish=async()=>{if(!admin)return;setSaving(true);setMsg("");const slug=form.slug||form.title.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");const {data:{user}}=await s.auth.getUser();const {data,error}=await s.from("newsletter_articles").insert({...form,slug,author_id:user?.id,published:true}).select("*").single();if(error){setMsg(error.message);setSaving(false);return}if(data)await fetch("/api/newsletter/notify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({article:data})});setOpen(false);setForm({title:"",slug:"",category:"Qur’an",excerpt:"",content:"",cover_emoji:"✦"});await load();setSaving(false);setMsg("Newsletter published. Subscribers were notified.");};
 return <main><SiteNav/><div className="shell"><header className="hero"><span>1MUSLIM NEWSLETTER</span><h1>Learn. Reflect. Stay connected.</h1><p>Long-form reflections, learning notes, and useful reminders from 1Muslim.</p><div className="topicRow"><b>Subscribe by topic</b>{topics.map(t=><button key={t.id} className={subs.includes(t.id)?"topic on":"topic"} onClick={()=>void toggle(t.id)}>{t.name}{subs.includes(t.id)?" ✓":""}</button>)}</div></header>
 {admin&&<section className="admin"><div><small>ADMIN PUBLISHING</small><h2>Create newsletter</h2><p>Only the 1Muslim admin account can publish newsletters.</p></div><button onClick={()=>setOpen(true)}>＋ Create newsletter</button></section>}
 {msg&&<div className="msg">{msg}</div>}
 <section className="grid">{articles.map(a=><Link className="card" href={"/newsletter/"+a.slug} key={a.id}><div className="thumb"><span>{a.cover_emoji}</span><small>1MUSLIM · {a.category}</small></div><div className="body"><span>{new Date(a.created_at).toLocaleDateString()}</span><h2>{a.title}</h2><p>{a.excerpt}</p><strong>Read article →</strong></div></Link>)}</section>
 {open&&<div className="modal"><div className="modalCard"><div className="modalHead"><h2>Create newsletter</h2><button onClick={()=>setOpen(false)}>×</button></div>{(["title","slug","category","excerpt","content","cover_emoji"] as const).map(k=><label key={k}>{k.replace("_"," ")}{k==="content"?<textarea value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}<button className="publish" onClick={()=>void publish()} disabled={saving}>{saving?"Publishing…":"Publish newsletter"}</button></div></div>}
 </div><style jsx>{styles}</style></main>
}
const styles=`
.shell{max-width:1120px;margin:auto;padding:45px 20px 90px;color:var(--text)}.hero{border:1px solid var(--line);border-radius:26px;padding:30px;background:linear-gradient(145deg,#101812,#080d09)}.hero>span,small{font-size:9px;letter-spacing:.16em;font-weight:900;color:#89a58e}.hero h1{font-size:clamp(32px,6vw,58px);line-height:.98;letter-spacing:-.06em;margin:12px 0}.hero p{color:var(--muted);max-width:650px}.topicRow{display:flex;gap:7px;flex-wrap:wrap;align-items:center;margin-top:24px}.topicRow b{font-size:11px;margin-right:4px}.topic{border:1px solid var(--line);background:var(--panel);color:var(--muted);border-radius:999px;padding:8px 11px;font-size:10px}.topic.on{background:#dbe9c4;color:#071008}.admin{margin-top:14px;border:1px solid #455a49;border-radius:20px;padding:18px;display:flex;justify-content:space-between;gap:15px;align-items:center;background:#0e1710}.admin h2{margin:4px 0}.admin p{color:var(--muted);font-size:11px}.admin button,.publish{border:0;border-radius:999px;background:#dbe9c4;color:#071008;padding:11px 15px;font-weight:900;font-size:10px}.msg{margin:12px 0;padding:12px;border:1px solid var(--line);border-radius:12px;color:#b9cbbd;font-size:11px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:20px}.card{border:1px solid var(--line);border-radius:20px;overflow:hidden;background:var(--panel2);text-decoration:none;color:inherit}.thumb{height:175px;position:relative;display:grid;place-items:center;background:radial-gradient(circle at 70% 25%,#1c604a,#07130c 65%)}.thumb span{font-size:70px}.thumb small{position:absolute;top:12px;left:12px;color:#dbe9c4}.body{padding:16px}.body>span{font-size:9px;color:#83918a}.body h2{font-size:19px;line-height:1.08;margin:8px 0}.body p{font-size:11px;line-height:1.55;color:var(--muted);min-height:52px}.body strong{font-size:10px}.modal{position:fixed;inset:0;background:rgba(0,0,0,.72);display:grid;place-items:center;z-index:100;padding:18px}.modalCard{width:min(680px,100%);max-height:90vh;overflow:auto;background:#0b110d;border:1px solid var(--line);border-radius:22px;padding:20px}.modalHead{display:flex;justify-content:space-between;align-items:center}.modalHead button{background:none;border:0;color:white;font-size:25px}.modalCard label{display:block;text-transform:capitalize;font-size:10px;font-weight:800;color:#aab6ae;margin-top:12px}.modalCard input,.modalCard textarea{width:100%;box-sizing:border-box;margin-top:6px;background:#060a07;border:1px solid var(--line);color:white;border-radius:10px;padding:10px;font:inherit}.modalCard textarea{min-height:180px;resize:vertical}.publish{margin-top:16px;width:100%}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.grid{grid-template-columns:1fr}.admin{align-items:flex-start;flex-direction:column}}
`;
