"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import SiteNav from "../../components/SiteNav";
import ModerationActions from "../../components/ModerationActions";
import {createClient} from "../../../utils/supabase/client";
type Report={id:string;target_type:"post"|"profile"|"comment"|"live"|"community";target_id:string;reason:string;status:string;created_at:string;reporter_id:string};
export default function ModerationDesk(){
 const [authorized,setAuthorized]=useState(false),[loading,setLoading]=useState(true),[reports,setReports]=useState<Report[]>([]),[message,setMessage]=useState("");
 const load=async()=>{const db=createClient();const {data,error}=await db.from("moderation_reports").select("id,target_type,target_id,reason,status,created_at,reporter_id").order("created_at",{ascending:false}).limit(100);if(error)setMessage(error.message);else setReports((data||[]) as Report[])};
 useEffect(()=>{let active=true;(async()=>{const db=createClient();const {data}=await db.rpc("is_1muslim_admin");if(!active)return;setAuthorized(data===true);setLoading(false);if(data===true)await load()})();return()=>{active=false}},[]);
 const update=async(id:string,status:string)=>{const db=createClient();const {error}=await db.from("moderation_reports").update({status}).eq("id",id);if(error)setMessage(error.message);else await load()};
 return <main style={{minHeight:"100vh",background:"#07120e",color:"#e7f5ec"}}><SiteNav/><div style={{maxWidth:1120,margin:"auto",padding:"40px 20px"}}><span style={{color:"#8de9b1",letterSpacing:3}}>1MUSLIM / ADMIN OPERATIONS</span><h1 style={{fontSize:"clamp(34px,5vw,60px)",margin:"12px 0"}}>Moderation Desk <span style={{color:"#8de9b1"}}>◉</span></h1><p>Incoming reports, investigation and decisive action.</p>{loading?<p>Checking permissions…</p>:!authorized?<p>Administrator access required.</p>:<><div style={{display:"flex",gap:12,flexWrap:"wrap",margin:"24px 0"}}>{["open","reviewing","resolved","dismissed"].map(status=><div key={status} style={{background:"#10271b",padding:20,border:"1px solid #2b5e42",borderRadius:15,minWidth:135}}><strong style={{fontSize:26}}>{reports.filter(r=>r.status===status).length}</strong><p>{status.toUpperCase()}</p></div>)}</div>{message&&<p role="status">{message}</p>}{reports.map(r=><article key={r.id} style={{background:"#101f18",border:"1px solid #2b5640",borderRadius:18,padding:20,marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><strong>{r.target_type.toUpperCase()} · {r.status.toUpperCase()}</strong><small>{new Date(r.created_at).toLocaleString()}</small></div><p>{r.reason}</p><small>Target: {r.target_id} · Reporter: {r.reporter_id}</small><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap",marginTop:15}}>{r.target_type==="post"&&<Link href={"/posts/"+r.target_id}>View post ↗</Link>}{r.target_type==="profile"&&<Link href={"/profile/"+r.target_id}>View profile ↗</Link>}<select aria-label="Report status" value={r.status} onChange={e=>void update(r.id,e.target.value)} style={{padding:9,background:"#173527",color:"white",borderRadius:8}}>{["open","reviewing","resolved","dismissed"].map(v=><option key={v}>{v}</option>)}</select><ModerationActions targetType={r.target_type} targetId={r.target_id} onDeleted={()=>void update(r.id,"resolved")}/></div></article>)}{reports.length===0&&<p>No reports yet. Desk is clear. ✨</p>}</>}</div></main>
}
