"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import SiteNav from "../components/SiteNav";
import "./quran-studio.css";
type Chapter={id:number;name_simple:string;name_arabic:string;verses_count:number;revelation_place?:string;translated_name?:{name:string}};
const highlights=[{icon:"📖",title:"Read & Reflect",detail:"Arabic, translation and verse-by-verse exploration",href:"/elm-tent/quran"},{icon:"✍️",title:"My Verse Studio",detail:"Write reflections, annotate and connect ayat",href:"/elm-tent/quran"},{icon:"🎙️",title:"Tajwīd Journey",detail:"Practice recitation, starting with Al-Fātiḥah",href:"/recording-studio/shahadah"},{icon:"✦",title:"Qur'an Community",detail:"Discuss and share meaningful verses",href:"/community"}];
export default function QuranStudioHome(){
 const [chapters,setChapters]=useState<Chapter[]>([]),[query,setQuery]=useState(""),[view,setView]=useState<"surahs"|"popular">("surahs"),[last,setLast]=useState<{chapter:number;verse:number}>({chapter:1,verse:1}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{try{const raw=localStorage.getItem("1muslim-quran-progress");if(raw){const v=JSON.parse(raw);if(Number.isInteger(v.chapter)&&v.chapter>=1&&v.chapter<=114)setLast({chapter:v.chapter,verse:Number(v.verse)||1})}}catch{}const controller=new AbortController();fetch("https://api.quran.com/api/v4/chapters?language=en",{signal:controller.signal}).then(r=>{if(!r.ok)throw Error("Unavailable");return r.json()}).then(d=>setChapters(d.chapters??[])).catch(e=>{if(e.name!=="AbortError")setError("Could not load the surah list. Please try again.")}).finally(()=>setLoading(false));return()=>controller.abort()},[]);
 const current=chapters.find(c=>c.id===last.chapter);
 const filtered=useMemo(()=>{const term=query.trim().toLowerCase();let items=view==="popular"?chapters.filter(c=>[1,2,18,36,55,67,112,113,114].includes(c.id)):chapters;return items.filter(c=>!term||String(c.id)===term||c.name_simple.toLowerCase().includes(term)||c.name_arabic.includes(query)||c.translated_name?.name.toLowerCase().includes(term))},[chapters,query,view]);
 return <main className="qsPage"><SiteNav/><div className="qsShell">
 <section className="qsHero"><div className="qsOrnament" aria-hidden="true">۞</div><span className="qsEyebrow">1MUSLIM · QUR'AN STUDIO</span><p className="qsBismillah" lang="ar" dir="rtl">بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</p><h1>Let the Qur’an<br/><em>illuminate your day.</em></h1><p className="qsSubtitle">Read. Listen. Reflect. Learn together. Your personal space to explore the words of Allah.</p><div className="qsSearch"><span aria-hidden="true">⌕</span><input aria-label="Search surahs" placeholder="Search a surah by name or number…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear search">×</button>}</div><div className="qsHeroActions"><button className={view==="surahs"?"active":""} onClick={()=>setView("surahs")}>☷ All 114 Surahs</button><button className={view==="popular"?"active":""} onClick={()=>setView("popular")}>✧ Popular</button><Link href="/elm-tent/quran">Open Reader ↗</Link></div></section>
 <div className="qsContent"><section className="qsContinue"><div className="qsSectionHead"><div><span className="qsEyebrow">YOUR JOURNEY</span><h2>Continue reading</h2></div><span className="qsPill">✦ A moment of reflection</span></div><Link href={"/elm-tent/quran?chapter="+last.chapter+"&verse="+last.verse} className="qsContinueCard"><div><span className="qsEyebrow">PICK UP WHERE YOU LEFT OFF</span><h3 lang="ar" dir="rtl">{current?.name_arabic||"الفاتحة"}</h3><strong>Surah {current?.name_simple||"Al-Fatihah"}</strong><small>{current?.translated_name?.name||"The Opening"} · Verse {last.verse}</small></div><span className="qsContinueArrow">Continue →</span></Link></section>
 <section className="qsTools"><div className="qsSectionHead"><div><span className="qsEyebrow">EXPLORE & GROW</span><h2>Make every verse a journey</h2></div></div><div className="qsToolGrid">{highlights.map((h,i)=><Link key={h.title} href={h.href} className={"qsTool qsTool"+i}><span className="qsToolIcon">{h.icon}</span><strong>{h.title}</strong><p>{h.detail}</p><span className="qsToolArrow">Explore ↗</span></Link>)}</div></section>
 <section className="qsSurahs"><div className="qsSectionHead"><div><span className="qsEyebrow">THE NOBLE QUR’AN</span><h2>{view==="popular"?"Popular surahs":"Explore the surahs"}</h2></div><span className="qsPill">{filtered.length} chapters</span></div>{error&&<p role="alert">{error}</p>}{loading?<p className="qsLoading">Loading the surahs…</p>:<div className="qsChapterGrid">{filtered.map(c=><Link key={c.id} href={"/elm-tent/quran?chapter="+c.id} className="qsChapter"><span className="qsChapterNum">{c.id}</span><div><strong>{c.name_simple}</strong><small>{c.translated_name?.name||"Qur'an"} · {c.verses_count} ayat</small></div><span className="qsChapterArabic" lang="ar" dir="rtl">{c.name_arabic}</span><span className="qsChapterGo">↗</span></Link>)}{!filtered.length&&!error&&<p>No surahs match your search.</p>}</div>}</section>
 <footer className="qsFooter">✦ Qur’an text and chapter information are retrieved from Quran.com’s API. <Link href="/elm-tent/quran">Enter the verse reader</Link></footer></div></div></main>
}
